.github/workflows/main.yml, .goreleaser.yml
Releases can be triggered just by push a tag which follows semver convention (`v1.2.3`).
--- 
I did not set up notarization (yet), so the darwin binaries on 10.15 (Catalina) will prompt the popup, such as:
Additionally it seems that Mac will show this warning after downloading the darwin ZIP file:
We can look into notarization as part of a separate PR.
--- 
Closes #31
=> Add GitHub workflow & GoReleaser

.github/CONTRIBUTING.md, Makefile, README.md, version/version.go
This change effectively enforces developers to build through the make target
and prevents server of version `0.0.0` from ever appearing in the wild.
As for the makefile logic:
- if the version is not provided we source the latest one from GitHub API
- in the "happy path" (being online and GitHub's API working correctly) `make build` "just works"
- otherwise (e.g. when offline) we can still build e.g. via `VERSION=0.1.0 make build`
=> Update installation & contribution instructions & add Makefile

commands/completion_command.go, internal/filesystem/errors.go, internal/filesystem/file.go, internal/filesystem/filesystem_test.go, internal/filesystem/types.go, internal/filesystem/uri.go, internal/filesystem/uri_unix.go, internal/filesystem/uri_unix_test.go, internal/filesystem/uri_windows.go, internal/filesystem/uri_windows_test.go, internal/lsp/file.go, internal/lsp/file_handler.go, internal/lsp/file_handler_test.go, internal/lsp/file_handler_unix.go, internal/lsp/file_handler_unix_test.go, internal/lsp/file_handler_windows.go, internal/lsp/file_handler_windows_test.go, internal/lsp/position.go, internal/terraform/exec/exec_test.go, langserver/handlers/complete_test.go, langserver/handlers/did_open_test.go, langserver/handlers/formatting_test.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go, langserver/handlers/initialize_test.go, langserver/handlers/shutdown_test.go
Closes #71 
Closes #72 
--- 
Tested in a Windows VM:
=> Fix failing tests and path parsing on Windows

internal/terraform/exec/exec.go
=> terraform/exec: Treat TempDir related vars as safe to pass through

internal/terraform/lang/config_block.go, internal/terraform/lang/datasource_block.go, internal/terraform/lang/datasource_block_test.go, internal/terraform/lang/hcl_block.go, internal/terraform/lang/provider_block.go, internal/terraform/lang/provider_block_test.go, internal/terraform/lang/resource_block.go, internal/terraform/lang/resource_block_test.go, internal/terraform/lang/types.go, internal/terraform/schema/schema_storage.go, internal/terraform/schema/schema_storage_mock.go, internal/terraform/schema/schema_storage_test.go
=> Add support for completing labels

internal/terraform/errors/errors.go, internal/terraform/schema/watcher.go, langserver/handlers/initialize.go
This improves the UX a little bit when user tries to open a directory which has not been `terraform init`'d.
```
2020/05/05 10:05:46 service.go:56: Preparing new service ...
2020/05/05 10:05:46 langserver.go:65: Starting server (pid 69133) ...
...
2020/05/05 10:05:46 exec.go:114: Running /usr/local/bin/terraform ["version"] in "/Users/jamesbayer/Documents/workspace/terraform-getting-started"...
2020/05/05 10:05:46 exec.go:140: terraform run (/usr/local/bin/terraform ["version"], in "/Users/jamesbayer/Documents/workspace/terraform-getting-started", pid 69135) finished with exit code 0
2020/05/05 10:05:46 initialize.go:85: Found compatible Terraform version (0.12.24) at /usr/local/bin/terraform
2020/05/05 10:05:46 schema_storage.go:266: Adding workspace for watching: …
```
=> terraform: Report uninitialized workspace

docs/USAGE.md
The language server seems to work well from Emacs lsp-mode so far. I documented one issue that I ran into with autocomplete on resource blocks in #100.
This PR is to add usage instructions to USAGE.md. Usage may be easier in the future if lsp-mode supports terraform-ls automatically, but for now I think we need to register a new client ourselves.
=> Add emacs instructions to USAGE.md

.github/workflows/main.yml, .goreleaser.yml
This is in preparation for https://github.com/hashicorp/terraform-ls/issues/49 as we can't publish any artifacts to releases.hashicorp.com without the signature.
cc @aeschright - FYI we could also verify the signature when installing the LS in VSCode. I'm just not sure what's the best workflow there and whether to bundle the pubkey (probably more secure, less convenient for potential updates) or pull it down from somewhere on demand (theoretically less secure, but more convenient for updates).
=> build: Sign archives checksum

internal/context/context.go, internal/context/errors.go, internal/context/signal_cancel.go
Fixes #79
This addresses the problem of potentially conflicting keys by turning keys into pointers, which will always be unique, even if the string-based internal name is the same (either intentionally or by accident).
=> context: Refactor and fix duplicate key

internal/hcl/errors.go, internal/hcl/hcl.go, internal/hcl/hcl_test.go, internal/source/source.go, internal/source/source_test.go, internal/terraform/lang/config_block.go, internal/terraform/lang/config_block_test.go, internal/terraform/lang/datasource_block.go, internal/terraform/lang/hcl_block.go, internal/terraform/lang/hcl_block_type.go, internal/terraform/lang/hcl_parser.go, internal/terraform/lang/hcl_parser_test.go, internal/terraform/lang/labels.go, internal/terraform/lang/parser.go, internal/terraform/lang/parser_test.go, internal/terraform/lang/provider_block.go, internal/terraform/lang/resource_block.go, internal/terraform/lang/schema.go, internal/terraform/lang/types.go, langserver/handlers/complete.go
Closes #18
As described in that issue, this only adds support for the blocks which have schema provided by providers, supporting other blocks is generally tracked under #36
=> textDocument/complete: Complete first level keywords

go.mod, go.sum, internal/lsp/completion.go, internal/mdplain/mdplain.go, internal/mdplain/mdplain_test.go, internal/terraform/lang/config_block.go, internal/terraform/lang/config_block_test.go, internal/terraform/lang/datasource_block.go, internal/terraform/lang/datasource_block_test.go, internal/terraform/lang/parser.go, internal/terraform/lang/parser_test.go, internal/terraform/lang/provider_block.go, internal/terraform/lang/provider_block_test.go, internal/terraform/lang/resource_block.go, internal/terraform/lang/resource_block_test.go, internal/terraform/lang/schema.go, internal/terraform/lang/types.go, internal/terraform/schema/schema_storage.go, langserver/handlers/complete_test.go, vendor/github.com/hashicorp/terraform-json/schemas.go, vendor/modules.txt
Move descriptions to the documentation field, update to terraform-json 0.5.0 that has additional description support, etc.
Using the `documentation` instead of `detail` gives it a better look in VS Code at least:
(my misspelling aside)
=> Improve UX of completion items

langserver/langserver.go
This presents a solution to problems that were discovered as part of #103 and #119
It follows gopls' implementation which doesn't have any concurrency either.
It does *not* address #8 but it significantly decreases the likelihood of in-flight conflicts. The only conflicts that may still occur is when provider schema is reloaded and any request leveraging the schema is in-flight at that time.
Longer-term we could look into parallelising unrelated requests which involve different files, but the real performance gain may be negligible, because it's unlikely that a single user would be working on more than 1 file at any given time.
=> langserver: Make requests sequential

.gitignore, internal/filesystem/file.go, internal/filesystem/file_test.go, internal/filesystem/filesystem.go, internal/filesystem/filesystem_test.go, internal/filesystem/types.go, internal/lsp/file.go, internal/lsp/file_change.go, internal/lsp/file_change_test.go, langserver/handlers/did_change.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go
fix #34
add support for file partial update.
- personally I want to make `func (fc *fileChange) Range() hcl.Range` to return a pointer, which is convenient to check whether to apply full content replace or partial update, but it seems need to change the interface and other parts, please confirm whether I should do in this way.
=> Partial update

langserver/handlers/did_change.go
I was under the impression that sequence of version numbers must be consecutive. According to the spec this is a wrong assumption:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#versionedTextDocumentIdentifier
```ts
interface VersionedTextDocumentIdentifier extends TextDocumentIdentifier {
/**
* The version number of this document. If a versioned text document identifier
* is sent from the server to the client and the file is not open in the editor
* (the server has not received an open notification before) the server can send
* `null` to indicate that the version is known and the content on disk is the
* master (as speced with document content ownership).
*
* The version number of a document will increase after each change, including
* …
```
=> textDocument/didChange: Avoid flagging non-consecutive versions

internal/hcl/errors.go, internal/hcl/hcl.go, internal/hcl/hcl_test.go, internal/hcl/types.go, internal/lsp/completion.go, internal/terraform/lang/config_block.go, internal/terraform/lang/config_block_test.go, internal/terraform/lang/datasource_block.go, internal/terraform/lang/datasource_block_test.go, internal/terraform/lang/hcl_block.go, internal/terraform/lang/hcl_block_type.go, internal/terraform/lang/hcl_parser.go, internal/terraform/lang/hcl_parser_test.go, internal/terraform/lang/parser.go, internal/terraform/lang/parser_test.go, internal/terraform/lang/provider_block.go, internal/terraform/lang/provider_block_test.go, internal/terraform/lang/resource_block.go, internal/terraform/lang/resource_block_test.go, internal/terraform/lang/types.go, internal/terraform/lang/utils.go, langserver/handlers/complete.go, langserver/handlers/complete_test.go
Related: #12 
- in your test case, when `Line:   2, Column: 5`, the Byte should be `21` but not `20`
- add some corner case for func `TokenAtPosition`
- I just filter the results in the last step, please confirm whether we should filter the candidates before putting them into the candidate list
- tested in vscode, it's ok for this feature
=> Add support for autocomplete based on a prefix

docs/USAGE.md
=> Add VS Code instructions, sort list alphabetically

internal/terraform/lang/config_block.go, internal/terraform/lang/config_block_test.go, internal/terraform/lang/parser.go
Closes #12 
Ideally we should probably be limiting the number of items we pull out from whatever data storage, but the data is currently just schema and the schema is currently stored in memory, so it's cheap to just pull out everything and then cut it while constructing the completion list 🤷 
We can revisit later.
=> textDocument/complete: Use isIncomplete for >100 items

internal/lsp/completion.go, internal/terraform/lang/config_block.go, internal/terraform/lang/config_block_test.go, internal/terraform/lang/parser.go, internal/terraform/lang/types.go, internal/terraform/lang/utils.go
Depends on #132 
--- 
This seemingly small change has a positive effect on the UX while completing in the middle of an existing token, where clients can correctly highlight parts of completion candidates.
--- 
As mentioned in the comment in code, this doesn't work (yet) for block types (e.g. `resource`, `data`, `provider`). It probably should, but some refactoring is necessary to make that work and realistically changing of block type is far less likely to occur in real scenarios, so it's ok to take on that tech debt.
=> textDocument/complete: Pass TextEdit instead of static text

commands/serve_command.go, internal/context/context.go, internal/terraform/exec/exec.go, langserver/handlers/service.go
This PR raises the default timeout from `10s` to `30s` to reflect the original timeout may not be sufficient for a combination of a few providers with large schemas used in the same config and slower disk I/O.
It seems pragmatic to accommodate such cases, but slow I/O is painful in general and configuration gets more fragile with more providers you add (e.g. because one API may be down, which makes applies stop half-way through etc.), so these users will suffer either way and this patch is not meant to solve all their problems, just to help them suffer _less_.
=> Make Terraform exec timeout configurable

internal/terraform/exec/exec.go
Closes #138 
This should address many use cases where some form of external auth provider is being looked up by the provider or state backend.
e.g. https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html in case of Kubernetes or `az` (Azure CLI) in case of AzureRM.
and also allow authentication from behind a corporate proxy, which can be configured on the workstation in such a way that the address of the proxy server is in standard environment variables.
We pass through all variables that are given to the server, which means that these could be reused between different workspaces, but this should be fairly safe for now, because
a) the language server doesn't execute `terraform` command that could do damage when provided wrong variables. We are working with the …
=> terraform/exec: Pass through all environment variables

internal/lsp/completion.go, internal/terraform/exec/exec.go
=> fix: os.Environ() returns KEY=val, not just keys

internal/terraform/errors/errors.go, internal/terraform/lang/parser.go, internal/terraform/schema/schema_storage.go, internal/terraform/schema/schema_storage_test.go, internal/terraform/schema/watcher.go
This relaxes the version constraints as we now know where to find the lock file in 0.13+.
This also enables support for any 0.12 prereleases.
Closes #111 
I removed the upper bound constraint from the watcher as I reckon/hope that the lock file location won't change - and if it does, then the worst case scenario is that we will report the workspace as uninitialised.
I assume we may start constraining the parser at some point, but that's a problem for another day.
=> terraform: Support 0.13 version

docs/USAGE.md
I added vim-lsp instruction for Vim8 users and grouped vim family and sorted list alphabetically.
I fixed it because I'm a Vim8 user and not NeoVim, the current instruction contains only for NeoVim.
However, at the time of this writing, the vim-lsp and coc.nvim now supports both Vim8 and NeoVim each other (contrary to the intuition from the name).
So this fix is not required, but I'd suggest it would be helpful for someone like me.
=> Add vim-lsp instruction

internal/mdplain/mdplain.go
I assume/hope this doesn't cause issues (it might, since the stdout is used as a communication channel?), but it's bad practice for any internal package to print stuff to stdout either way.
We could pass logger down there, but I think that such simple package doesn't even need logging at this point.
=> internal: Remove print stmts from mdplain

internal/terraform/errors/errors.go, internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, langserver/handlers/initialize.go
Closes #83 
This does *not* yet introduce support for more complex hierarchies
but enables formatting even for files in directories
which do not have any plugin cache.
The lack of plugin cache is now emitted just as a log message.
Informing the user at this point wouldn't be very helpful
because we don't know where the module usually gets init'd from yet,
i.e. whether the plugin cache is even expected *there*.
Complex hierarchies will be addressed in other PRs in iterative steps as part of #32
=> Treat schema availability as not essential

langserver/handlers/initialize.go
=> fix detection of single file during initialization

internal/terraform/rootmodule/errors.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/types.go, langserver/handlers/formatting.go
=> Make formatting work regardless of initialization state

langserver/handlers/did_open.go
Ideally I'd like to refactor the logic here to _not_ parse paths as string, but given that this is merely a rendering/UX detail, I think it can be done in a separate PR.
I assume there will be need for some more path-parsing logic in https://github.com/hashicorp/terraform-ls/issues/179 anyway, so it can be developed in that context.
=> Display '.' in warning message for top directory

internal/terraform/rootmodule/root_module.go
This is fixing a bug where we would detect plugin lock file change as module change and vice versa. Therefore the server would attempt to update plugins when module change and update module cache when plugins change. This could lead to a situation where obtaining schema errors out because the plugin lock file wasn't written to the disk yet (modules are updated first during `init`).
This was introduced as part of #167 (so far unreleased 😅 )
The watcher logic is entirely untested at this point - something to address.
I'm just not sure what the best testing strategy there is yet. Should we entirely mock out the watcher, or genuinely update real files on the filesystem in TMPDIR? I feel like that question needs to be answered, but I'd like to answer it in a separate PR.
=> rootmodule: Fix schema/module update detection

.github/workflows/release.yml
Takes advantage of recent improvements in hc-releases.
This should finally allow us to run the whole release pipeline in the GitHub Action end-to-end with scoped keys.
=> build: Scope hc-release publish

internal/context/context.go, internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/root_module_manager_mock.go, internal/terraform/rootmodule/root_module_manager_mock_test.go, internal/terraform/rootmodule/root_module_manager_test.go, internal/terraform/rootmodule/types.go, internal/terraform/rootmodule/walker.go, internal/terraform/rootmodule/walker_mock.go, internal/terraform/schema/schema_storage.go, internal/terraform/schema/schema_storage_mock.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go, langserver/handlers/service.go, langserver/handlers/service_mock_test.go, langserver/langserver_mock.go
Closes #188 
There is some more work needed around cancellation (some tech debt is now a little more exposed as a result of this PR 😄 ), but that's resolvable separately as part of https://github.com/hashicorp/terraform-ls/issues/195
=> terraform/rootmodule: Make walker async by default

.github/workflows/release.yml
This would aid potential debugging of failed releases.
=> build: print out hc-releases version after installation

langserver/handlers/did_open.go
This is in reaction to https://discuss.hashicorp.com/t/no-root-module-found/10944
It's likely this will generate more pressure to resolving https://github.com/hashicorp/terraform-ls/issues/128 but it would at least get people closer to the point where it works (assuming they setup auth wrapper or use local state) and make the message more actionable.
=> textDocument/didOpen: Enrich warning message

.github/workflows/ci.yml, .github/workflows/release.yml
As written in the comment, I fixed it to read version from `.go-version` instead of hard-coding.
=> Read go version from .go-version on GitHub Actions

.github/workflows/ci.yml, .github/workflows/release.yml
Simplifies reading the file by just using a `cat` and the built-in functions for `::set-output`: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
=> Remove third party GH action

internal/context/context.go, internal/terraform/exec/exec.go, internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/types.go, langserver/handlers/formatting.go, langserver/handlers/formatting_test.go, langserver/handlers/service.go
Depends on #219
Closes #211
Technically #219 allows use of any Terraform version (hence fixes the bug). This patch just provides better UX for the incompatible versions.
=> Gate formatting capability on v0.7.7+

commands/serve_command.go, docs/TROUBLESHOOTING.md
This aims to help with debugging https://github.com/hashicorp/terraform-ls/issues/217
=> Introduce CPU & memory profiling

internal/terraform/exec/exec.go, internal/terraform/exec/exec_test.go, internal/terraform/rootmodule/root_module_manager_mock_test.go, internal/terraform/rootmodule/root_module_manager_test.go, langserver/handlers/complete_test.go, langserver/handlers/formatting_test.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize_test.go
This reverts commit b5a949697a06624262b27c841e4882d55d95852b.
Closes #226
=> Revert "Pass -no-color to terraform"

internal/terraform/rootmodule/root_module.go
Closes #218 
There are still some edge cases where blocking would be better solution than just logging or surfacing of these errors, but that can be covered as part of #8
=> rootmodule: log errors after loading is finished

go.mod, internal/hcl/hcl.go, internal/hcl/hcl_test.go, internal/terraform/lang/parser_test.go
Fixes #217 
The user will often produce invalid/incomplete config as they type, so diagnostics are ignored - which is by design in case of the parser. However the parser also assumes that the sequence of tokens it receives from the lexer is valid, i.e. that the [important check for invalid tokens](https://github.com/hashicorp/hcl/blob/ea60f7f2a65052437fb8373fb6434597a4a9e079/hclsyntax/token.go#L174-L193) is **not** ignored.
There are some configs which one might expect to be "parseable", e.g.
```hcl
provider "null" {
}
variable "name" {
default = "
}
```
but the parser isn't ready to deal with such config yet and the lexer returns the trailing `}` as string literal.
If we wanted to perform completion near the opening quote we would be completing in the context of a string literal. We …
=> fix: Prevent parsing invalid tokens

internal/hcl/hcl.go, internal/hcl/hcl_test.go, internal/terraform/lang/config_block.go, internal/terraform/lang/hcl_block.go, internal/terraform/lang/hcl_block_type.go, internal/terraform/lang/hcl_parser_test.go, internal/terraform/lang/parser_test.go, internal/terraform/lang/types.go
Fixes #238 
The HCL parser apparently isn't fully ready to parse isolated blocks terminated by newline and so we just append EOF instead of newline, which the parser can safely deal with.
This technically fixes the bug in the sense that CPU no longer spikes, but the completion context is a bit off, so that still needs fixing:
```hcl
resource "aws_ecr_lifecycle_policy" "policy" {
for_each = toset(var.repo_name
}
```
> config_block.go:112: completing block: **"repo_name"**, &hcl.Range{Filename:"main.tf", Start:hcl.Pos{Line:2, Column:24, Byte:70}, End:hcl.Pos{Line:2, Column:33, Byte:79}}
Technically we don't support RHS completion yet anyway, so there should be no context being matched, or something, but certainly not variable name being treated as block name/type.
=> fix: Append EOF instead of newline

internal/terraform/rootmodule/root_module.go, langserver/handlers/did_open.go
This slightly improves logging, where previously we'd log error from plugin cache updating separately and then report 0 errors from loading a module, now all the loading stages are treated the same in terms of error reporting.
The relevant error is however still (intentionally) ignored as watcher invokes these methods:
https://github.com/hashicorp/terraform-ls/blob/2347f8dcc34685b179b6bd054f9774ec68b80345/internal/watcher/watcher.go#L89-L94
Secondly this also improves the message we show when there is no root module found, to be more helpful until https://github.com/hashicorp/terraform-ls/issues/222 is implemented and reflect that the message is related to the directory, rather than file.
=> Improve root module discovery error handling

commands/inspect_module_command.go, docs/TROUBLESHOOTING.md, internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/root_module_manager_test.go, internal/terraform/rootmodule/types.go, internal/terraform/rootmodule/walker.go, langserver/handlers/initialize.go, langserver/handlers/service.go, main.go
Closes #225 
This aims to provide another way of debugging complex hierarchies, which is a problem people tend to run into.
```
$ terraform-ls inspect-module .
```
```
2 root modules found in total at /var/workspace/tf-test/github
- /var/workspace/tf-test/github
- 3 errors:
- terraform version 0.11.0 is not supported in schema storage (supported: >= 0.12.0)
- terraform version 0.11.0 is not supported in parser (supported: >= 0.12.0)
- cannot update schema as schema cache is not available
- 1 modules
- nested-root (./nested-root)
- /var/workspace/tf-test/github/nested-root
- 0 errors
- 0 modules
```
=> New command: inspect-module

docs/SETTINGS.md, internal/settings/settings.go, internal/settings/settings_test.go, langserver/handlers/did_open.go, langserver/handlers/did_open_test.go, langserver/handlers/initialize.go
Fixes #235 
It's worth noting that this does _not_ allow the user to just "force-pair" the root module. Any referenced root module still has to reference the folder being opened in the editor as a module, otherwise it will not be matched.
Force-pairing is something we could consider but that would likely require some UI changes, maybe even an entirely separate config option as we wouldn't be able to pick the right path from a list. Also I would like to first understand the use cases for such feature before implementing it.
=> settings: Support relative paths to root modules

langserver/handlers/initialize.go
We evaluate symlinks for explicit paths and the side effect of doing that is also checking if the target directory actually exists.
This would previously fail the initialization and cause the LS to be effectively shut down.
It seems more logical to just raise a warning and let the user carry on as they may have some other valid paths and the server may still be useful for auto-formatting which doesn't require a root module.
=> Warn and skip invalid root module paths

docs/SETTINGS.md, internal/settings/settings.go, internal/terraform/rootmodule/path.go, internal/terraform/rootmodule/walker.go, langserver/handlers/initialize.go
fix #250
not support glob pattern yet.
another question: if users change the settings in editor side, for now the vscode extension would remind user to reload. But I wonder implementing configurationChanged event in language server side  might be a better way?
=> add support for specify exclude root module path

internal/hcl/hcl.go, internal/hcl/types.go, internal/lsp/completion.go, internal/lsp/file_change.go, internal/terraform/lang/datasource_block.go, internal/terraform/lang/parser.go, internal/terraform/lang/provider_block.go, internal/terraform/lang/resource_block.go, internal/terraform/lang/types.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go, langserver/handlers/service.go, langserver/handlers/symbol.go
This provides initial support for symbols navigation. Only supports symbols within the active file, and only jumps to provider, resource, and datasource blocks.
Closes #263
=> Symbols Support

internal/terraform/lang/parser.go, langserver/handlers/handlers_test.go, langserver/handlers/symbols_test.go
We previously ignored all diagnostics, which includes both minor and major, the latter of which prevent the HCL parser from parsing anything and therefore resulting in `nil` being returned from `ParseBlockFromTokens` which was then unexpected outcome for `Blocks()`.
_Example of such invalid config_
```hcl
provider "aws"
access_key = "value"
}
```
The crash didn't occur during completion because it uses some other position-based methods which would already stop before stepping further into the parser internals and in particular into `ParseBlockFromTokens`. Symbol listing however is not position based and so listing symbols on an invalid config leads to a crash.
=> fix: prevent crash when listing symbols

docs/SETTINGS.md, internal/context/context.go, internal/settings/settings.go, langserver/handlers/execute_command.go, langserver/handlers/execute_command_rootmodules_test.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go, langserver/handlers/service.go
This PR ensures the uniqueness of the exported commands across different language servers (with a `terraform-ls.` prefix, this is a common practice) and an additional `<commandPrefix>.`, this latter ensures multiple instances of the language server can run side by side, it will become the clients responsibility to send requests with the correct command name, the `commandPrefix` is only enabled if specified in the `initializationOptions` for the server.
```
"executeCommandProvider": {
"commands": ["1234.terraform-ls.rootmodules"]
}
```
Closes #278
=> Unique command names

internal/terraform/rootmodule/plugin_lock_file.go
As mentioned in https://github.com/hashicorp/terraform-ls/issues/282 v0.14 uses different path for the plugin lock file. This PR reflects that.
Currently we only use the path to detect whether there are any plugins initialized and to detect plugin changes, i.e. we don't care about the file contents which made this change easier than originally expected.
Closes #282
=> Add support for upcoming Terraform v0.14

.github/CONTRIBUTING.md
We don't use make for building anymore, as mentioned in https://discuss.hashicorp.com/t/how-to-build-terraform-ls/17302 and we no longer vendor dependencies.
=> Update contribution docs

internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/root_module_manager_test.go, internal/terraform/rootmodule/testdata/README.md, internal/terraform/rootmodule/testdata/uninitialized-root/main.tf
This was just overlooked in the big PR https://github.com/hashicorp/terraform-ls/pull/281
#281 did (correctly) provide basic schema in cases where e.g. modules were initialized, but no provider schema available (e.g. because of backend auth).
This patch just delivers on the originally stated promise as mentioned in the changelog - i.e. to provide limited schema even to folks which have not initialized anything at all, i.e. there is no `.terraform` folder.
=> Avoid ignoring schema for uninitialized module

internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/types.go
This fixes a race condition which is difficult to reproduce, but https://github.com/hashicorp/terraform-schema/issues/7 has the relevant panic trace.
This practically delivers on the promise mentioned here https://github.com/hashicorp/terraform-ls/blob/612cceb828a8e2abc89088582a6fd6c10c3ca509/internal/terraform/rootmodule/root_module.go#L245-L249
In other words I thought this was already done but I must have missed it in https://github.com/hashicorp/terraform-ls/pull/281
=> Avoid panic by initing universal schema early

langserver/handlers/execute_command.go
This action is actually sent from the server with the expectation that (some) clients will catch it and open the completion box, as demonstrated in #300 
However the clients which do not catch it will just pass it back to the server and assume that it's just another valid command.
Here we avoid "registering" that command alongside others (as we don't want to confuse clients like VS Code which do support it), but we just catch the request, if it makes it back to the server and ignore it.
Fixes #306
=> Capture editor.action.triggerSuggest to avoid errors

go.mod, go.sum
Fixes #118
This brings in https://github.com/creachadair/jrpc2/pull/32 which addresses the long-standing problem with strict unmarshaling (where unknown fields in JSON would result in errors) as described in https://github.com/creachadair/jrpc2/issues/31
This is also kind of prerequisite to migrating to the gopls' struct types and away from `sourcegraph/go-lsp` (as per https://github.com/hashicorp/terraform-ls/issues/117), since gopls types do not declare custom unmarshalers, unlike my custom fork of `go-lsp`
https://github.com/hashicorp/terraform-ls/blob/229568e8948dfc58cb98a616bce467cf8ac31fd4/go.mod#L31
=> Bump jrpc2 to latest version

internal/terraform/exec/exec.go, internal/terraform/exec/mock/executor.go, internal/terraform/exec/types.go, internal/terraform/rootmodule/root_module.go, internal/terraform/rootmodule/root_module_manager.go, internal/terraform/rootmodule/types.go, langserver/handlers/did_open.go, langserver/handlers/service.go
fix #106.
there are some points that have not been considered. such as if current dir is in `IncludeRootModule` or `ExcludeRootModule`
=> ask for init if current folder is empty root module

.github/workflows/ci.yml
This reflects recent change of default branch from `master` to `main`.
=> github: Reflect branch changes

commands/serve_command.go, internal/context/context.go, langserver/handlers/handlers_test.go, langserver/handlers/initialize.go, langserver/handlers/service.go
=> Expose server version via LSP

internal/lsp/hover.go, langserver/handlers/hover.go
fix #317
tried to return empty `lsp.Hover`, however, the vscode client will complain: `unsupported Markup content received. Kind is: `
The official recommendation is just return `null` from here: https://github.com/Microsoft/language-server-protocol/issues/261
generally two ways：
* make lsp protocol model fields be pointer type.
* in handle function, just return pointer type result
It seems we generate the lsp protocol model, so I just choose the second way.
everything seems fine:
=> fix issue when hoverData is nil

internal/langserver/cmd/cmd.go, internal/langserver/cmd/cmd_args.go, internal/langserver/handlers/command/rootmodules.go, internal/langserver/handlers/execute_command.go, internal/langserver/handlers/execute_command_rootmodules_test.go
This is mostly to decouple the helper functions away from the handler and make extra folder/package for command handlers as that should make it easier to find commands in the hierarchy as we add more of them.
I'd love for the command handler tests to also live in that package, but it means we'd have to extract some functions as "test utils" somewhere so it can be used outside of the `handlers` package, but similar to other PRs - I'm taking one step at a time.
=> Refactor command handlers

internal/langserver/handlers/command/init.go, internal/langserver/handlers/execute_command_init_test.go
This may not have any practical difference, but I did notice the handler was using a helper for creating a file handler from a file uri. This change uses the directory helper. I was concerned that the calling code was passing a file URI as well, which I thought was not the ideal interface we wanted to expose.
As it turns out, the calling code does in fact pass a directory URI, so I think the intention was for the `uri` to be a folder all along
=> Use directory ilsp helper in init command

internal/langserver/handlers/did_open.go
This is just fixing an unforeseen side effect of https://github.com/hashicorp/terraform-ls/pull/333
where we'd pass full file path to `askInitForEmptyRootModule` treating it like a directory path, when it isn't.
I guess the cleanest way of prevent similar bugs would be to have clearer separation between file handlers and dir handlers, instead of interfaces hiding parts of the "universal" handler.
=> fix: pass dir handler to init command

internal/langserver/handlers/command/validate.go
It is hard to actually test this without the corresponding integration on the client side, but it's more or less copy-n-paste from the init command, which I did test through the server-initiated progress from the dialog opened in `didOpen`.
=> Report progress for validate command

go.mod, go.sum, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/semantic_tokens.go, internal/langserver/handlers/semantic_tokens_test.go, internal/langserver/handlers/service.go, internal/lsp/semantic_tokens.go, internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go, internal/lsp/token_types.go
I have only implemented the first handler and the protocol allows omitting the rest via capability negotiation, so we can add the other ones later.
Client always sends `textDocument/semanticTokens/full` almost immediately after `didOpen` and `didChange`, which means that we may not have all the schema at that point. `workspace/semanticTokens/refresh` would enable us to refresh tokens dynamically from the server side as we know more schema, e.g. when `terraform version` and/or `terraform providers schema -json` finish. As a result _not_ supporting this call initially may provide occasionally "flickering UX" (colours change as the user types), but the upside is that it can't be any worse than it is, because we are just _enriching_ the highlighting and the static grammar in VSCode extension …
=> Implement textDocument/semanticTokens (semantic highlighting)

internal/langserver/handlers/semantic_tokens.go, internal/langserver/handlers/semantic_tokens_test.go, internal/lsp/semantic_tokens.go
This is a follow-up to a recently merged (but not yet released 😅 ) #331 which I discovered by manually testing the server with VS Code extension, which supports deltas.
Attached test describes the scenario and fails without the patch:
```
--- FAIL: TestSemanticTokensFull_clientSupportsDelta (0.00s)
langserver_mock.go:121: [-32601] method not found
```
=> Fix detection of client semantic token support

docs/SETTINGS.md, internal/context/context.go, internal/langserver/handlers/command/init.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/did_save.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/langserver/progress/progress.go, internal/settings/settings.go, internal/terraform/rootmodule/root_module.go
This creates a new configuration object for the language server called `ExperimentalFeatures` which allows users to opt into specific features which may not be ready to be on by default. The first feature is calling `terraform validate` on save (with the saved file as the target directory).
This does work as expected, however the user experience is a bit awkward in 2 cases:
- Validate is not run on open, only on save. This makes it awkward when opening your project, you will not see any validation errors for the file in focus until you save.
- Modules is supported, but the experience isn't ideal. For simplicity, in #323 we do not run `terraform validate` when a module file is saved. This is because it could be referenced/downstream from multiple root modules (we don't know which root …
=> Validate On Save

.goreleaser.yml
This mimics build targets of latest Terraform (core) version, e.g.
https://releases.hashicorp.com/terraform/0.14.3/
Closes #342
=> Add support for linux/arm64

.github/workflows/release.yml
According to the [Changelog](https://github.com/goreleaser/goreleaser-action/blob/master/CHANGELOG.md#changelog) there are no changes which would affect us, but we will confirm that soon enough during the next release.
=> github: bump GoReleaser Action to v2

.github/dependabot.yml
Closes #64 
I chose dependabot as that seems most popular choice based on anecdotal evidence from Terraform provider repositories (which also migrated to dependabot from Renovate) and also because it seems to have reached parity of features which we need (`go mod tidy` namely) with Renovate.
I looked briefly at Snyk and concluded it doesn't support Go yet: https://support.snyk.io/hc/en-us/articles/360006581898-Upgrading-dependencies-with-automatic-PRs
=> github: Enable dependabot for Go dependencies

go.mod, go.sum
This should also enable dependabot to automatically raise PRs for further updates.
=> Bump terraform-exec to 0.12.0

main.go
Depends on https://github.com/hashicorp/vscode-terraform/pull/512 being merged _and_ released.
Closes #185
=> Print help (and version) to stdout

internal/cmd/version_command.go, main.go
Closes #184
This unblocks https://github.com/hashicorp/terraform-ls/issues/127 (once JSON output is being used by the VS Code extension).
This introduces a new subcommand `terraform-ls version` with (optional) `-json` flag.
The existing `terraform-ls -version` still works and will continue working, but won't have the JSON flag - at least for now.
=> cmd: Introduce version JSON output

internal/langserver/handlers/service.go
This fixes a bug which was introduced in the recently merged big PR #385 - presumably just oversight.
=> Fix: Add missing TF exec context for didOpen

internal/terraform/module/module_loader.go
This fixes a bug which is described in the inline comment. It seems quite unlikely end-user would hit it, but I did manage to hit it in CI test (`TestModuleManager_ModuleCandidatesByPath`) which panicked due to timeout (which I unfortunately do not have available as I retried it and it passed).
I also verified at least once that with sufficient pressure the codepath is hit:
```
$ go test ./internal/terraform/module -run=TestModuleManager_ModuleCandidatesByPath -count=750 -timeout=5s -p=1 -v | grep "no available capacity"
2021/02/03 15:29:59 module_loader.go:83: no available capacity, retrying dispatch
```
but I couldn't get a reliable repro unfortunately.
=> ModuleLoader: Avoid deadlock by retrying operation dispatch

internal/terraform/module/module_loader.go
Closes #186
While the number of operations in parallel is capped, we can still _overutilize_ the available CPU as per 
https://github.com/hashicorp/terraform-ls/blob/d31f6b4bdd99a3e6b889ac0b0a9aac5fc5a6bb84/internal/terraform/module/module_manager.go#L46
(prior to #385)
and now
https://github.com/hashicorp/terraform-ls/blob/f5ddf9ac740469f762b3aa9175b40187e0e44a7e/internal/terraform/module/module_loader.go#L25-L26
This patch therefore ensures  that except for single-core we never run more threads than there is CPUs available, which should provide some relief to users with many modules in the hierarchy.
=> Utilize CPU better when loading modules

internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go
Fixes #387 
This affects most cases where there is more than 2 tokens on the same line (typically blocks with 2 labels, like resources and data sources), in which case the `deltaStartChar` was being miscalculated.
=> ilsp: Fix miscalculated semantic tokens

internal/terraform/module/module_loader.go, internal/terraform/module/module_ops_queue.go, internal/terraform/module/module_ops_queue_test.go
This fixes a number of bugs I found while testing this both manually in VS Code and by running tests with high enough `-count`.
1. Deadlock could occur when retry of dispatch is attempted, because while `run()` is executing, another goroutine (e.g. one executing a different operation) could have finished and triggered another `tryDispatchingModuleOp` which then filled the channel and the next `tryDispatchingModuleOp` triggered from `run()` as a result of retry would block, therefore blocking the main loop.
- This was resolved by running retry `tryDispatchingModuleOp` in an additional goroutine
2. `tryDispatchingModuleOp` can get triggered by many threads at the same time and its original implementation left an opportunity for race condition due to `queue.Peek()` relying on `queue.Len()` …
=> module loader: Avoid deadlock

internal/schemas/gen/gen.go
This is to address a situation where two providers of the same `Name` (but different namespace) appear in the list.
Currently this would result in
```tf
buildkite = {
source = "buildkite/buildkite"
}
buildkite = {
source = "jradtilbrook/buildkite"
}
```
which is invalid due to the duplication.
Hence this patch just appends a number to make it unique, i.e. the above becomes
```tf
buildkite-47 = {
source = "buildkite/buildkite"
}
buildkite-48 = {
source = "jradtilbrook/buildkite"
}
```
=> schema preload: Ensure provider names are unique

internal/langserver/errors/errors.go, internal/langserver/handlers/command/init.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/formatting.go, internal/terraform/module/errors.go, internal/terraform/module/terraform_executor.go
Closes #398 
I did initially consider printing out the `$PATH` too, but then I realized it may not even fit in a popup such as the one VS Code uses, or that it can't be formatted in any useful way.
=> Improve messaging when TF installation is not found

internal/terraform/module/watcher.go, internal/terraform/module/watcher_test.go
When lock file changes we always reload the schema but it is likely that provider versions may have also changed and therefore we need to reload that too.
=> watcher: Refresh versions when plugin lockfile changes

go.mod, go.sum, internal/cmd/completion_command.go, internal/context/context.go, internal/decoder/decoder.go, internal/langserver/handlers/complete.go, internal/langserver/handlers/document_link.go, internal/langserver/handlers/document_link_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/semantic_tokens.go, internal/langserver/handlers/service.go, internal/langserver/handlers/symbols.go, internal/lsp/links.go, internal/terraform/module/module_ops.go
Depends on https://github.com/hashicorp/hcl-lang/pull/8
Depends on https://github.com/hashicorp/terraform-schema/pull/10
--- 
This adds links to relevant documentation for providers via hover data and `documentLink` method, which then results in the following UX in VS Code:
Maybe this is not the best UX, but we don't have any control over how clients (such as VS Code) use the `documentLink` and if at all. Sublime Text for example doesn't implement it at all, so we are left with just hover:
I don't have strong opinion on how we link to docs UX-wise, but I think we could just roll it out and see how people (dis)like it.
Relatedly the UTM parameters will help us identify any click-throughs to the Registry using any of these two features. All URLs have these parameters appended:
- …
=> Add docs links to document and hover

internal/schemas/gen/gen.go
The provider apparently created a Registry release entry, but haven't yet uploaded any artifacts due to what seems to be a cancelled release job:
https://github.com/HewlettPackard/terraform-provider-oneview/runs/1892292461
=> Exclude HPE OneView from preloaded providers

.goreleaser.yml
This was unfortunately missed in #392
Custom publishers in GoReleaser do not inherit any environment variables by default, which includes (crucially) `$HOME` variable which in turn is used by the new AWS auth mechanism and that's causing the following failure on release attempt:
```
• custom publisher 
• publishing                cmd=[hc-releases upload-file /home/runner/work/terraform-ls/terraform-ls/dist/terraform-ls_0.14.0_SHA256SUMS.sig]
• publishing                cmd=[hc-releases upload-file /home/runner/work/terraform-ls/terraform-ls/dist/terraform-ls_0.14.0_freebsd_amd64.zip]
• Verifying S3 credentials...
cmd=hc-releases
• Verifying S3 credentials...
cmd=hc-releases
⨯ NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or …
```
=> build: Fix release job by passing HOME to hc-releases

.goreleaser.yml
Follow up on #412 #413 and #414 
Forth time is the charm?
=> goreleaser: Swap colon for equal sign to assign ENV vars correctly

README.md
Closes #361 
Packages are being built automatically after each release for all documented distributions.
=> Readme: Document Linux package based installation

.github/workflows/ci.yml, Makefile, internal/langserver/handlers/session_mock_test.go, internal/terraform/exec/exec_test.go
Fixes #206
See also https://github.com/hashicorp/terraform-exec/issues/129
=> Test for race conditions

go.mod, go.sum, internal/langserver/handlers/symbols_test.go, internal/lsp/completion.go, internal/lsp/symbols.go, internal/lsp/token_encoder.go, internal/lsp/token_types.go
This PR introduces support for a few expression types as described in more detail in https://github.com/hashicorp/hcl-lang/pull/16
This is a first step and _future PRs_ will bring support for _more expression types_, so that we can _eventually_ resolve the following:
- https://github.com/hashicorp/terraform-ls/issues/37
- https://github.com/hashicorp/terraform-ls/issues/38
- https://github.com/hashicorp/terraform-ls/issues/92
- https://github.com/hashicorp/terraform-ls/issues/93
- https://github.com/hashicorp/terraform-ls/issues/191
=> Add initial support for expressions

internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/langserver/handlers/workspace_symbol.go, internal/langserver/handlers/workspace_symbol_test.go, internal/lsp/symbols.go, internal/terraform/module/types.go
Depends on #411 
--- 
Closes #315 
Closes #423
=> Add workspace-wide symbol navigation

internal/terraform/module/watcher_test.go
This test showed up as flaky here https://github.com/hashicorp/terraform-ls/pull/427/checks?check_run_id=2089364081#step:10:34 which presumably was just a result of the short delay.
=> fix flaky test: Increase delay in watcher test

internal/langserver/handlers/handlers_test.go
This is to address this test failure:
https://github.com/hashicorp/terraform-ls/runs/2089667487#step:10:17
=> langserver/handlers: Increase delay to avoid flaky test

internal/schemas/gen/gen.go
This is to address recent failures caused by what is likely a broken release:
```
Error: Failed to install provider
Error while installing zerotier/zerotier v0.1.47: checksum list has unexpected
SHA-256 hash 4db7c72387a4c0332067706e46598acc0f55991edfe63aeb63af699289977cbd
(expected 3b29b99e109b817b031239ef491d8f9ddafc4264439224fe89d72cead45678a6)
```
=> schemas: Exclude zerotier from schema preload list

go.mod, go.sum
This brings in a fix for a bug causing duplicates in label/provider completion as mentioned in https://github.com/hashicorp/terraform-schema/pull/36
=> bump hashicorp/terraform-schema to cbd37641c308

.goreleaser.yml
We'll generate both for backwards compatibility, although js-releases (which VS Code extension specifically uses) should only require the suffixed variant once https://github.com/hashicorp/js-releases/pull/9 is merged
=> goreleaser: Generate key ID suffixed sig files

.github/workflows/ci.yml, .github/workflows/release.yml
This is to take advantage of recently announced changes:
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
=> build: Reduce scope of GHA token

internal/schemas/gen/gen.go
With the list being a moving target I'm thinking if it's worth looking into checking via the API the availability/init-ability somehow, before attempting `init`. 🤔 
But this is just a quick solution to unblock releases for now.
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
nirmata/nirmata: no available releases match the given constraints 
```
=> preloaded schemas: ignore nirmata/nirmata

internal/langserver/handlers/command/init.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/formatting.go, internal/langserver/handlers/service.go, internal/terraform/module/module_ops.go, internal/terraform/module/terraform_executor.go
We used to track Terraform exec path alongside each module which is because technically every module may require different TF version and relatedly different exec path. However that exec path was in practice always the same for all modules, which is also why the new module state store doesn't store it anymore.
It is possible that we'll revisit this idea of tracking exec path per module, but for now it's just better to remove it.
=> handler/formatting: Remove unused module query

.github/workflows/release.yml
gpg apparently uses tty for printing warnings (in this case likely about trust level for the new key)
Because there's no valid tty in GitHub Actions (or any other CI) we reflect that by passing extra flags to gpg.
This should address the following error during release:
```
gpg: key 34365D9472D7468F/B0B441097685B676: error sending to agent: Inappropriate ioctl for device
gpg: error reading '[stdin]': Inappropriate ioctl for device
gpg: import from '[stdin]' failed: Inappropriate ioctl for device
```
If this doesn't work then we can consider swapping that `echo | gpg` command for https://github.com/hashicorp/ghaction-import-gpg which is used by most Terraform providers AFAIK.
=> ci: Fix broken key importing

.goreleaser.yml
This is to apply a patch similar to https://github.com/hashicorp/terraform-ls/pull/474 which should address the following failure observed during release:
```
• signing artifacts
• signing                   cmd=[gpg -u *** --output dist/terraform-ls_0.16.0_SHA256SUMS.sig --detach-sign dist/terraform-ls_0.16.0_SHA256SUMS]
• signing                   cmd=[gpg -u *** --output dist/terraform-ls_0.16.0_SHA256SUMS.***.sig --detach-sign dist/terraform-ls_0.16.0_SHA256SUMS]
• gpg: signing failed: Inappropriate ioctl for device
cmd=gpg
• gpg: signing failed: Inappropriate ioctl for device
cmd=gpg
• gpg: signing failed: Inappropriate ioctl for device
cmd=gpg
• gpg: signing failed: Inappropriate ioctl for device
cmd=gpg
⨯ release failed after 867.67s error=sign: gpg failed
```
=> goreleaser: Fix broken signing

.github/workflows/release.yml
Apparently the TTY-related problems (which I attempted to fix in https://github.com/hashicorp/terraform-ls/pull/474 and https://github.com/hashicorp/terraform-ls/pull/475) surfaced as `Inappropriate ioctl for device` were caused by passphrase requirement on the key I wasn't aware of.
We could use the passphrased key, but there seems little benefit in terms of risk (when both are stored in the same place) and it increases complexity of the pipeline.
=> ci: Change secret name for GPG key

.goreleaser.yml
GoReleaser doesn't seem to support templating in the `signature` field (yet), so we can instead just pass the sig filename directly in `args` where templating _is_ supported.
=> goreleaser: Fix templating in signs

.goreleaser.yml
In an attempt to work around the unsupported templating in `signature` I didn't realize that steps following after `signs`, such as custom publishers will only pick up the files per `signature`, which - if left undefined are duplicate and cause releases to fail while uploading the same file twice to GitHub.
=> goreleaser: avoid producing duplicate sig files

internal/langserver/handlers/service.go, internal/state/provider_schema.go, internal/state/provider_schema_test.go, internal/state/state.go
Fixes #479 
This accounts for a case where users don't have explicit provider requirement in their configuration, but use Terraform 0.13+ (which outputs provider schemas with new addresses).
Generally `ProviderSchema()` is not meant to ever return `nil, nil`, which other logic in `terraform-schema` relies on:
https://github.com/hashicorp/terraform-schema/blob/ad0461b4382716039f6d35e8fd9bd8599458285c/schema/schema_merge.go#L70-L77
I also added some extra logging in "hot paths" which users are likely to hit and where knowing more may aid debugging in the future.
Legacy addresses will unfortunately not be eliminated in the near future, despite how we refer to them (legacy) as there's currently no plan for making explicit `source` argument required in Terraform v1.
We can guide people to help …
=> fix: prevent crash for legacy provider lookups

internal/cmd/serve_command.go, internal/langserver/langserver.go
=> Increase request concurrency & make it configurable

internal/schemas/gen/gen.go
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
datastax/astra: no available releases match the given constraints 
```
=> schemas: Exclude datastax/astra from pre-generated schemas

go.mod, go.sum, internal/decoder/decoder.go, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_open.go, internal/lsp/completion.go, internal/lsp/token_encoder.go, internal/lsp/token_types.go, internal/state/module.go, internal/terraform/module/builtin_references.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_manager.go, internal/terraform/module/module_ops.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
Builds on https://github.com/hashicorp/hcl-lang/pull/36
Builds on https://github.com/hashicorp/terraform-schema/pull/41
--- 
Some known (most likely desirable) features were intentionally left out from the MVP, but are tracked individually and will be eventually implemented:
- variable `type` declarations: https://github.com/hashicorp/terraform-ls/issues/490
- references to variables & locals (via `var.x` or `local.x`): https://github.com/hashicorp/terraform-ls/issues/491
- step-based completion: https://github.com/hashicorp/terraform-ls/issues/492
- showing interpolated expression value on hover: https://github.com/hashicorp/terraform-ls/issues/495
- recognition of individual expressions when nested: https://github.com/hashicorp/terraform-ls/issues/496
- references to `module` outputs & …
=> Add support for traversals/references

internal/langserver/handlers/cancel_request_test.go, internal/langserver/handlers/service.go, internal/langserver/handlers/session_mock_test.go
Cancellation was fixed via https://github.com/hashicorp/terraform-ls/pull/489
Here I'm just adding a test (which fails when concurrency is set to `1`).
Closes #314
=> Add test for '$/cancelRequest' method

docs/commands.md, internal/langserver/handlers/command/module_callers.go, internal/langserver/handlers/execute_command_module_callers_test.go
As discussed this field is actually no longer needed by the VS Code extension and so it's better to keep the API minimal.
https://github.com/hashicorp/vscode-terraform/pull/633#issuecomment-843592045
=> cmd/module.callers: Remove rel_path field

internal/schemas/gen/gen.go
This is due to the old namespace having a broken build without linux/amd64 for some reason:
https://github.com/okta/terraform-provider-okta/issues/480
=> schemas: Exclude oktadeveloper/okta

internal/cmd/completion_command.go, internal/filesystem/document.go, internal/filesystem/document_metadata.go, internal/filesystem/document_test.go, internal/filesystem/filesystem.go, internal/filesystem/filesystem_metadata.go, internal/filesystem/filesystem_test.go, internal/filesystem/types.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/did_open_test.go, internal/lsp/file.go, internal/lsp/file_handler.go, internal/terraform/module/module_ops_queue_test.go
Adding the language id so we could distinguish between tfvars and terraform files
This will assist the implementation for #50 and #519.
=> Add LanguageID to file

go.mod, go.sum
Fixes https://github.com/hashicorp/terraform-ls/issues/286
Depends on https://github.com/hashicorp/terraform-schema/pull/50
=> Add support for provisioners

go.mod, go.sum, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/hover_test.go
This brings hashicorp/terraform-schema#56 to add support for
`isRequired` in variable schema.
=> Bump `terraform-schema`

internal/terraform/module/module_manager.go
So that completion/hover/highlighting is available for variable
`default`.
Fixes #537
=> Support variable `default`

internal/schemas/gen/gen.go
This should address the following CI failure:
https://github.com/hashicorp/terraform-ls/pull/555/checks?check_run_id=2848589136#step:6:63
```
error: terraform core version not supported by configuration
```
=> internal/schemas: Bump TF version requirement to ~> 1

internal/langserver/handlers/code_lens.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go
Because it is not trivial to omit codeLens support from the server capabilities with gopls' LSP structs, we just pretend that we support it but don't return any.
Fixes #560
=> Mock out code lens support

go.mod, go.sum, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go
Fixes #492
Step-based completion basically offers only the top-most reference (from hierarchy perspective) that matches what is already written (any characters after `=`). In other words completion for empty expression such as `attribute = # HERE` would bring up only top-level references.
Additionally this patch also provides decoding for references to addressable elements within some non-primitive types - namely attributes within object expressions, map entries, and list entries.
Depends on https://github.com/hashicorp/hcl-lang/pull/56
=> Provide (less verbose) step-based completion

go.mod, go.sum, internal/decoder/decoder.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_open.go, internal/state/module.go, internal/terraform/module/builtin_references.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_ops.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This is to reflect some name refactoring upstream, as described in https://github.com/hashicorp/hcl-lang/pull/61
=> refactoring: Reference -> ReferenceTargets

.goreleaser.yml
To match upstream https://github.com/hashicorp/homebrew-tap/blob/afc17338a13fd83f623c83872fc03b4f386726d2/.github/workflows/publish-formula-update.yml#L40-L41 and prevent any confusion on hashibot performing the activity, which it is not.
=> Update goreleaser homebrew Git commit information

internal/cmd/inspect_module_command.go, internal/langserver/handlers/did_change_workspace_folders.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/state/module.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_manager.go, internal/terraform/module/module_manager_test.go, internal/terraform/module/module_ops_queue.go, internal/terraform/module/types.go, internal/terraform/module/walker.go, internal/terraform/module/walker_queue.go, internal/terraform/module/watcher.go, internal/terraform/module/watcher_mock.go
Closes #482 
Depends on https://github.com/hashicorp/vscode-terraform/issues/627
=> Support multiple folders natively

internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/terraform/module/walker.go
This was introduced as part of https://github.com/hashicorp/terraform-ls/pull/502 (i.e. the bug thankfully isn't part of a release)
--- 
Due to limited channel buffer size, the walker queueing would be blocked on any 2nd path here:
https://github.com/hashicorp/terraform-ls/blob/cf0650f2b75415b135f222f6bd4d1ab787409064/internal/langserver/handlers/initialize.go#L153
or here
https://github.com/hashicorp/terraform-ls/blob/cf0650f2b75415b135f222f6bd4d1ab787409064/internal/langserver/handlers/initialize.go#L190
and it would remain blocked forever as it would also block starting the walker and therefore consumption from the channel.
Attached test times out without the patch.
=> fix: increase walker queue buffer & start walking early

go.mod, go.sum, internal/langserver/handlers/references.go
This (seemingly minor) change allows the user to use more fine-grained approach when looking for references.
Namely if they request references to a nested attribute/block, they receive references to that and _not_ to the parent (outermost) block:
They can still request all references to the block itself and any nested references for targets within the block if they click on the block header:
=> references: use innermost target instead of outermost

go.mod, go.sum
Previously reference origins/addresses (such as `var.foo`) would be matched against addressable targets (attributes or blocks) in a strict fashion where addresses have to match exactly.
This patch makes origins scope & type aware as per https://github.com/hashicorp/hcl-lang/pull/68 which in turn helps us "optimistically" recognize references to targets of unknown type.
References to `var.test` are not recognized (no data provided on hover, reference not semantically highlighted, no go-to-definition etc.) due to the variable not having explicit type.
On hover we display the closest known target (for clarity).
=> Make references scope & type aware

go.mod, go.sum
As demonstrated by config in https://github.com/hashicorp/terraform-ls/issues/585 there was a bug in the decoder which caused reference origins (addresses) to not be collected and then unavailable for "go to references" within dependent schemas, such as `resource` or `data` blocks.
This brings in an upstream patch https://github.com/hashicorp/hcl-lang/pull/70 which reflects dependent schemas.
Fixes #585
=> fix 'go to references' for resources & data sources

internal/langserver/handlers/did_open.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_manager.go, internal/terraform/module/module_ops.go, internal/terraform/module/types.go, internal/terraform/module/walker.go, internal/terraform/module/watcher.go
@Nepomuceno Do you think this would help in https://github.com/hashicorp/terraform-ls/pull/551 ?
I guess the `Enqueue` method could return the operation and make the caller do the actual queueing and potentially setting `Defer` function instead of passing it as argument, but that's mostly a stylistic concern that can be refactored later.
If this helps solving the problem I'd ship it. 🤷🏻‍♂️
=> Introduce Defer to module loader

internal/state/module.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_manager.go, internal/terraform/module/module_ops.go, internal/terraform/module/types.go, internal/terraform/module/walker.go, internal/terraform/module/watcher.go
As discussed in https://github.com/hashicorp/terraform-ls/pull/551#discussion_r674703187
=> Queue decoding of submodules asynchronously

go.mod, go.sum, internal/langserver/handlers/code_lens.go, internal/langserver/handlers/go_to_ref_target.go, internal/langserver/handlers/references.go
This still doesn't mean we can recognize references in arbitrarily deeply nested expressions - that will be addressed in https://github.com/hashicorp/terraform-ls/issues/496, but this PR at least addresses the lowest-hanging fruits.
Brings in the following upstream PRs:
- https://github.com/hashicorp/hcl-lang/pull/73
- https://github.com/hashicorp/hcl-lang/pull/74
=> fix: recognize references in lists and other complex types

go.mod, go.sum
Fixes #592 
This addresses the case of references nested within most common types of expressions (list, set, tuple, object or map). Remaining expression types are to be addressed as part of https://github.com/hashicorp/terraform-ls/issues/496
=> fix: recognize references in common nested expressions

internal/langserver/diagnostics/validate_diags.go
Previously we would suppress any diagnostics which do not have source context associated with them.
This for example means that if user attempted to run `validate` on uninitialized module they wouldn't receive any feedback at all - as if the configuration is valid.
This PR makes such diagnostics visible.
LSP technically makes [source range mandatory](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnostic) in the protocol - which seems kinda awkward given that they allow diagnostic to be associated with a directory URI.
We can however just pass an "empty" `0,0-0,0` range which satisfies the protocol and allows the diagnostic to still be displayed, as demonstrated in VS Code:
=> textDocument/publishDiagnostics: Publish any source-less warnings or errors

internal/context/context.go, internal/langserver/diagnostics/diagnostics.go, internal/langserver/diagnostics/diagnostics_test.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/service.go
Fixes #524 
--- 
The "silent delay" is an effect of VS Code not supporting progress reporting during command execution https://github.com/microsoft/vscode-languageserver-node/issues/528#issuecomment-541600565
=> fix: avoid publishing stale 'validate' diagnostics

go.mod, go.sum
This addresses one of two bugs reported in https://github.com/hashicorp/vscode-terraform/issues/707 , specifically in https://github.com/hashicorp/vscode-terraform/issues/707#issuecomment-891008775
The other bug is to be fixed on the client / extension side.
This brings in the following upstream patch https://github.com/hashicorp/hcl-lang/pull/77
=> fix: avoid crash on highlighting unknown tuple element

internal/langserver/handlers/command/init.go, internal/langserver/handlers/command/module_callers.go, internal/langserver/handlers/command/validate.go, internal/lsp/file_handler_unix_test.go, internal/uri/uri.go, internal/uri/uri_test.go
I ran into a weird situation where the Terraform VS Code extension would call the validate command with `uri=output:extension-output-%232` which was somehow silently accepted.
I can no longer reproduce that client-side bug to understand why this happened, but at least this patch will make that problem more visible next time it happens.
=> Always validate URI schema

go.mod, go.sum
=> fix: allow multiple variable validation blocks

internal/cmd/completion_command.go, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/workspace_symbol.go, internal/lsp/range.go, internal/lsp/symbols.go, internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go, internal/protocol/gen/gen.go, internal/protocol/protocol.go
Closes #604 
This will also allow us to bump the [upstream LSP client library](https://www.npmjs.com/package/vscode-languageclient) in the VS Code extension which would otherwise make the server crash upon initialization if bumped to `7.0.0` currently:
```
Error for "initialize" (ID 0): [-32602] invalid parameters: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool
```
Updated structs seem to work seamlessly with `8.0.0-next.1` version of the upstream LSP client library.
=> Bump LSP structs to gopls 0.7.0

.github/workflows/ci.yml
Default timeouts are actually 6 hours and our jobs should typically finish within minutes, so there's no point in waiting any longer.
=> github: Reduce jobs timeout from high default

docs/SETTINGS.md, internal/cmd/serve_command.go, internal/langserver/handlers/service.go, internal/settings/settings.go
=> internal: expose pending tf related options via init opts

docs/language-clients.md, internal/langserver/handlers/code_action.go, internal/langserver/handlers/code_action_test.go, internal/langserver/handlers/formatting.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/lsp/code_actions.go
This adds a code action to format a file based on the `editor.codeActionsOnSave` setting. This can either be a global setting or one specific to the terraform language.
Fixes #327
=> Format on save code action

.github/workflows/milestone-closed.yml, .github/workflows/release.yml, .goreleaser.yml
Assuming that we assign all issues and PRs queued up for a release to the relevant milestone, we can automate closing of that milestone and publish comments to inform subscribes users that the feature or bug fix was released upon the release.
This follows what the AWS provider does; for example https://github.com/hashicorp/terraform-provider-aws/issues/20047#issuecomment-876773674
=> ci: Automate milestone closing & commenting

go.mod, go.sum
Previously we didn't correctly limit the number of candidates returned for a label completion, which in some extreme cases would mean that for a resource we would send ~700 items just for AWS provider + any more hundreds for any other providers declared in the module.
This limits the items to 100 and expects the user to keep typing to filter the results.
This PR brings in https://github.com/hashicorp/hcl-lang/pull/85
=> fix: Limit label completion items to 100

.gitattributes, internal/decoder/decoder.go, internal/filesystem/filesystem.go, internal/filesystem/filesystem_test.go, internal/filesystem/types.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_close.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/service.go, internal/state/module.go, internal/state/module_test.go, internal/terraform/ast/ast.go, internal/terraform/ast/ast_test.go, internal/terraform/ast/module.go, internal/terraform/ast/variables.go, internal/terraform/module/module_ops.go, internal/terraform/parser/module.go, internal/terraform/parser/module_test.go, internal/terraform/parser/parser.go, internal/terraform/parser/testdata/invalid-mod-files/incomplete-block.tf, internal/terraform/parser/testdata/invalid-mod-files/missing-brace.tf, internal/terraform/parser/testdata/valid-mod-files-with-extra-items/.hidden.tf, internal/terraform/parser/testdata/valid-mod-files-with-extra-items/main.tf, internal/terraform/parser/testdata/valid-mod-files-with-extra-items/main.tf~, internal/terraform/parser/testdata/valid-mod-files/resources.tf, internal/terraform/parser/variables.go
Closes #562
This PR decouples some logic of the overgrown `module` package into `ast` and `parser`:
- `parser` is responsible for parsing `*.tf` and `*.tfvars` files - and potentially other future files we will support
- `ast` is responsible for representing the files and diagnostics so that they can be filtered accordingly (e.g. we can distinguish between autoloaded and not-autoloaded tfvars files)
=> Support standalone (not autoloaded) `*.tfvars` files

.github/workflows/ci.yml
Prior to this patch we would stop running any steps in a matrix job immediately when one of them fails.
For example if a single test fails on Linux, that would cause the Windows and macOS steps to stop. While this is a sensible strategy for cost saving it's sometimes helpful to know whether tests actually fail on other platforms or whether it's platform-dependent failure.
We have already applied conservative timeout to each step and our tests generally don't take very long to finish so the cost saving argument is not as strong here anyway.
Docs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
=> github: Keep running tests on other platforms upon failure

.github/workflows/ci.yml, go.mod, go.sum, internal/langserver/handlers/command/module_calls.go, internal/langserver/handlers/command/module_calls_test.go, internal/langserver/handlers/execute_command.go, internal/terraform/datadir/module_types.go
Adds a handler to return a list of modules in the current workspace to display client side.
Completes: https://github.com/hashicorp/vscode-terraform/pull/746
=> Module View Command Handler

docs/USAGE.md
Neovim v0.5 is released.
It has a [built-in lsp client](https://neovim.io/doc/user/lsp.html).
This PR is to add a usage instruction for users of this client.
=> docs: Add description for nvim built-in lsp

internal/schemas/gen/gen.go
This is to address the failing CI build which is caused by the fact that the provider only has a single release, which is a pre-release (beta1) and since we don't provide any version constraints in our generated configs it implicitly excludes prereleases.
https://github.com/hashicorp/terraform-ls/runs/4065743149?check_suite_focus=true#step:6:65
=> schemas: exclude ciphertrust

internal/terraform/module/module_loader.go
When a deep hierarchy is being indexed, there is a high chance that we reach the max. number of operations that can run at the same time and effectively hit a point where operations are repeatedly rescheduled for some time.
Logging this fact results in the message being all over the log and very spammy, so I'm proposing to remove it.
=> internal: Avoid logging when capacity is reached

docs/SETTINGS.md, internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/settings/settings.go, internal/settings/settings_test.go, internal/terraform/module/walker.go
This PR adds a new setting called `ignoreDirectoryNames` to the language server. It's now possible to send a list of directories on `initialize`, which should be ignored by the walker and never be indexed.
Closes #670
=> Implement ignorelist for module indexing

internal/state/module.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_loader_test.go, internal/terraform/module/testdata/single-root-no-modules/main.tf
This is a ~typo~ copy paste bug which was introduced early with the introduction of these operations in https://github.com/hashicorp/terraform-ls/pull/485
Attached test exhibits the behaviour.
This is blocker for https://github.com/hashicorp/terraform-ls/pull/700 where we rely on reference origins & targets to always be parsed.
=> terraform/module: fix reference collection skipping

internal/terraform/ast/variables.go, internal/terraform/parser/variables.go
This PR adds support for collecting variables from `*.tfvars.json` and `*.auto.tfvars.json` files in addition to `*.tfvars`.
Closes #519.
--- 
Users can find variables declared in JSON files when seeking symbols across the workspace.
Users can find a list of issues for JSON files in the problems tab.
=> Implement support for JSON variable files

internal/telemetry/noop.go
This was useful when implementing the telemetry features, but now it can make the log output unnecessarily verbose, which doesn't help especially when debugging other things, as usually that happens in a dev environment where telemetry is disabled.
=> telemetry: Disable logging when telemetry is disabled

internal/langserver/handlers/did_change_workspace_folders_test.go, internal/langserver/handlers/hooks_module.go, internal/langserver/handlers/service.go
I was able to reproduce this by removing a folder from a workspace, but I also noticed that the VS Code client in particular sends `shutdown` to the server instead of `didChangeWorkspaceFolder` with the removed folder, so we can't _really_ track module removals _yet_ until that client-side bug is addressed.
https://github.com/hashicorp/terraform-ls/blob/055cf0226f209e9b5cbfa95a9ec59d0fe1928c41/internal/state/module.go#L252-L255
I also noticed that the notifications for folder change would never work because we weren't passing the module manager down to the handler, so it would always error out 🙈  This was there since the beginning https://github.com/hashicorp/terraform-ls/pull/502
=> fix: Avoid crash in telemetry on module removal

internal/langserver/handlers/command/module_providers.go, internal/langserver/handlers/execute_command.go, internal/langserver/handlers/execute_command_module_providers_test.go, internal/langserver/handlers/service.go, internal/langserver/handlers/session_mock_test.go
This PR adds a new workspace command `module.providers`.
=> Introduce list module providers command

internal/langserver/diagnostics/diagnostics.go, internal/langserver/diagnostics/diagnostics_test.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_close.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/hooks_module.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/langserver/session/types.go, internal/state/module.go, internal/terraform/module/module_loader_test.go, internal/terraform/module/module_manager.go, internal/terraform/module/module_ops.go, internal/terraform/module/types.go, internal/terraform/module/walker.go, internal/terraform/module/watcher.go
Originally we would only publish diagnostics directly from the relevant (RPC request) handlers, such as from `textDocument/didOpen`, `textDocument/didChange` or `textDocument/didClose`.
This in principle introduced the requirement on the task scheduler to support blocking/synchronous execution as we didn't want to be publishing stale diagnostics before the parsing and decoding is actually finished. However, this execution combined with the amount of operations we need to run in different contexts makes this a complex implementation hard to reason about and harder to maintain. Consequently there is at least one bug 🐛  where duplicate operations are attempted to be scheduled and one of them will remain blocking forever, effectively causing a deadlock 🙀 . This bug was first discovered in …
=> refactor: decouple diagnostics from handlers into a hook

internal/langserver/handlers/initialize.go, internal/terraform/module/module_manager.go
We use module paths in many different places and we this ensure we will compare the same paths consistently and avoid duplicate entries in memdb.
There is unfortunately no easy way to test this as the potential problem would arise as part of a module operation which is executed asynchronously, and/or when publishing diagnostics, which is in itself hard to test currently.
This bug is more visible in https://github.com/hashicorp/terraform-ls/pull/714 and https://github.com/hashicorp/terraform-ls/pull/700 when you open a folder that has symlink somewhere in the path.
--- 
We will likely re-evaluate this decision more holistically (in the context of the whole codebase) in https://github.com/hashicorp/terraform-ls/issues/241
=> Avoid duplicate state entries (by avoiding symlink evaluation)

docs/commands.md, internal/langserver/handlers/command/module_calls.go
#632 and #712 introduced two new workspace commands. This PR updates the docs for both commands
=> Update docs with new workspace commands

docs/USAGE.md
Neovim now exposes a sync version of the formatting method. With the current example, in some cases, formatting was happening after a file was saved as the `formatting` method is async.
=> Update neovim formatting example to use the sync version

internal/schemas/gen/gen.go
This is to stop ignoring providers which are now `init`-able without issues and to add `nullstone-io/ns` which has invalid schema that Terraform v1.1 rejects when running most schema-related commands, such as `terraform providers schema -json`.
=> schemas: revise list of ignored providers

internal/langserver/handlers/execute_command_modules_test.go, internal/terraform/exec/exec_test.go, internal/terraform/module/module_manager_test.go
Closes https://github.com/hashicorp/terraform-ls/issues/549
~The `build` CI failure can be fixed by https://github.com/hashicorp/terraform-ls/pull/740~
=> skip and fix failing tests on Apple Silicon

internal/terraform/module/module_loader.go
This will cause indexing to take longer to finish on machines with >2 CPUs, but it should flatten the CPU spikes some users have reported in https://github.com/hashicorp/terraform-ls/issues/733
It is worth noting that this puts a bit more pressure on resolving https://github.com/hashicorp/terraform-ls/issues/5 / https://github.com/hashicorp/terraform-ls/issues/150
=> module loader: Reduce parallelism to 1/1 in all cases

internal/langserver/handlers/service.go
Previously we'd always send a notification to the client whenever reference counts changed. This would be ignored by the client if the code lens was disabled, so this patch is basically no-op from UX perspective, but it should save some overhead by not sending the notification at all when it's not needed.
=> fix: avoid code lens updates when disabled

go.mod, go.sum, internal/decoder/decoder.go
This is mainly to unblock https://github.com/hashicorp/terraform-ls/pull/758 without having to merge https://github.com/hashicorp/terraform-ls/pull/727 yet.
Upstream changes were introduced in https://github.com/hashicorp/terraform-schema/pull/84
=> deps: Update hashicorp/terraform-schema to latest rev

internal/cmd/inspect_module_command.go, internal/cmd/serve_command.go
While debugging https://github.com/hashicorp/terraform-ls/issues/733 Windows users have reported that CPU profile never gets written in their environment.
This is because CPU profile only gets written upon (graceful) shutdown which we perform by catching particular interrupt/termination signals. Prior to this patch however we were only catching Unix-native signals, which Windows never sends, resulting in dirty shutdowns and never giving the opportunity for a CPU profile to be written to disk.
See also: https://pkg.go.dev/os/signal#hdr-Windows and https://stackoverflow.com/a/35683558
=> fix: Catch OS agnostic interrupt signal

go.mod, go.sum, internal/langserver/handlers/complete_test.go, internal/schemas/gen/gen.go, internal/terraform/exec/exec_test.go
Closes #711
---
- replaced all `tfinstall` usage with `hc-install` which first looks for tf in filesystem and if didn't find, installs specified/latest version
- in `exec` moved tf version into function arguments
=> Switch to hc-install from tfinstall

internal/langserver/handlers/hooks_module.go, internal/state/installed_providers.go, internal/state/installed_providers_test.go, internal/state/module.go
Depends on https://github.com/hashicorp/terraform-schema/pull/89
Depends on https://github.com/hashicorp/terraform-ls/pull/761
According to manual testing with a single installed module from https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest this can reduce the amount of telemetry requests to about half (from 32 to 14).
There's probably more we can do here - e.g. avoid sending telemetry for unsaved data. This is not only extra overhead, but also pollutes the data with "unfinished" provider or backend names. However this would require more effort - probably queueing the telemetry data somewhere and then adding a hook which gets triggered by `textDocument/didSave`. Either way not something I wanted to tackle in this PR.
=> telemetry: Only send requests if data has changed

internal/langserver/handlers/complete_test.go, internal/langserver/handlers/go_to_ref_target.go, internal/langserver/handlers/go_to_ref_target_test.go, internal/langserver/handlers/service.go, internal/lsp/location_links.go, internal/state/provider_schema.go
Fixes #735 
Also fixes another bug where in `textDocument/definition` we previously checked `Declaration.LinkSupport` instead of `Definition.LinkSupport` client capability.
Lastly there was a (minor) bug in tests where we missed `textDocument` nesting, so link support was never tested.
=> fix: Return correct target selection range for definition/declaration

internal/schemas/gen/gen.go
This is to address the fact that the provider doesn't have any release other than pre-release, which makes it impossible to install without explicit version (which is how we install it internally).
=> schemas: Ignore zededa/zedcloud

internal/decoder/decoder.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_open.go, internal/state/module.go, internal/state/module_test.go, internal/terraform/module/module_loader.go, internal/terraform/module/module_loader_test.go, internal/terraform/module/module_ops.go, internal/terraform/module/operation/operation.go, internal/terraform/module/walker.go, internal/terraform/module/watcher.go
Closes https://github.com/hashicorp/terraform-ls/issues/618
---
Depends on:
* https://github.com/hashicorp/terraform-schema/pull/84
=> Introduce go-to-variable from `tfvars` files

.github/workflows/release.yml, .goreleaser.yml
This PR updates the release signing to use the internal HashiCorp signing service (signore).
Closes #688.
Update secrets before merging:
=> Sign releases using signore

ROADMAP.md
=> Q1 2022 Roadmap

internal/schemas/gen/gen.go
This is to address
```
Error: Incompatible provider version
Provider registry.terraform.io/jradtilbrook/buildkite v0.6.0 does not have a
package available for your current platform, linux_amd64.
Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```
https://github.com/hashicorp/terraform-ls/runs/5122097433?check_suite_focus=true#step:6:68
=> schemas: Ignore jradtilbrook/buildkite

internal/langserver/handlers/hooks_module.go, internal/langserver/handlers/service.go, internal/state/module.go
Add change hooks to the Module state store to trigger token refresh after specified parts of the schema are discovered after initialization.
Fixes #344
=> Enable Semantic Token Refresh

internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This is mostly for convenience in debug messages, which otherwise come through as not-very-descriptive `OpType(9)`.
=> Add String() for `OpTypeDecodeVarsReferences`

internal/schemas/gen/gen.go
This is to address the following
```
Error: Incompatible provider version
Provider registry.terraform.io/kvrhdn/honeycombio v0.3.0 does not have a
package available for your current platform, linux_amd64.
Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```
https://github.com/hashicorp/terraform-ls/runs/5245400640?check_suite_focus=true#step:6:67
=> schemas: exclude kvrhdn/honeycombio

internal/langserver/handlers/semantic_tokens_test.go, internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go, internal/lsp/token_types.go
This PR updates the type for block labels from string to enum member.
It's the first step in providing more contextual information on block labels. With a schema update, it will be possible to differentiate between multiple block labels. This will allow us to report two different tokens for block labels where the first one stays enum member and the second one becomes a string.
We've tried different token types, like `class`, `macro`, `method`, and `enumMember` and settled on the latter. `enumMember` makes the most sense from a semantic perspective and has good highlighting in the default themes.
Having semantic tokens for block labels enables better highlighting for nested blocks.
Before (no LS)
After (with LS)
For a smoother user experience, we propose to update the static grammar for …
=> Update semantic token block label type

.goreleaser.yml
TODO:
--- 
Closes #456
See relevant docs at https://goreleaser.com/customization/release/#github
```yaml
prerelease: auto
```
and https://goreleaser.com/customization/homebrew/
```yaml
skip_upload: true
```
=> goreleaser: Enable pre-release publishing

internal/langserver/handlers/service.go
The `/didSave` handler was missing WithModuleManager and WithExecutorFactory, which the validate command handler needs to find terraform to execute validate.
Closes #792
=> Fix validate on save

internal/cmd/serve_command.go
This PR updates the help section for the `serve` command.
Variables in arguments must be lower-case and without a `.`, e.g.
```
terraform-ls serve -cpuprofile='/Users/dbanck/tmp/profile-{{timestamp}}.pprof'`
```
=> Update help for `serve` command arguments

go.mod, go.sum
This is to bring https://github.com/hashicorp/terraform-schema/pull/94 in.
=> deps: Bump hashicorp/terraform-schema to faadc57bd40a

go.mod, go.sum, internal/terraform/datadir/module_types.go
This simplifies the relatively non-critical part of code which is responsible for detecting module source (which has the effect of displaying different icons in the UI).
Here I'm trading-off possibly less accuracy for faster compile times by removing go-getter as a dependency.
In GitHub CI, the cross-compilation was previously around 8-11mins:
- https://github.com/hashicorp/terraform-ls/runs/5336086783?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/5336082442?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/5335277276?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/5336105445?check_suite_focus=true
This should shave off at least a few minutes on average - the CI run associated with this PR reported `5m 33s`.
=> Remove go-getter & simplify module source detection

internal/langserver/handlers/complete_test.go, internal/terraform/module/watcher.go
Fixes #801 
Prior to this patch we would only decode the last submodule in the slice. This was because of a _common mistake_ documented in https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
i.e. we were passing a reference to the job functions which were executed well after the ranging over the slice was done, hence reusing the same reference, with the reference pointing to the last value in the last iteration.
I believe this was only introduced in the refactoring PR https://github.com/hashicorp/terraform-ls/pull/782 so if we patch it prior to the next release there would be no user affected.
Attached below is the same example as in the original bug report, now working:
=> fix: decode all submodules with the right path

README.md, docs/installation.md
This is to reflect the fact that we now have the ability to cut pre-releases.
I also decoupled the relatively verbose installation section, also reflecting the fact that in VSCode's & SublimeText's case this is not relevant.
=> docs: decouple installation & add stability section

.github/workflows/release.yml
This PR adds the `read` permission for packages for the release job. This is required to install the signore package.
=> Add packages `read` permission for release

internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go
Fixes #763
- https://github.com/hashicorp/vscode-terraform/issues/955
- https://github.com/hashicorp/terraform-ls/issues/816
=> internal/lsp: fix encoding of unknown semantic token types

internal/schemas/gen/gen.go
This is in reaction to the following
https://github.com/hashicorp/terraform-ls/runs/5419512936?check_suite_focus=true#step:6:47
```
Error: Incompatible provider version
Provider registry.terraform.io/harness-io/harness v0.1.15 does not have a
package available for your current platform, linux_amd64.
Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```
=> schemas/gen: exclude harness-io/harness

.github/workflows/ci.yml, .github/workflows/issue-comment-created.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/stale.yml
This allows us to be a little bit more defensive by not giving any workflows more permissions than they really need and use this safer default settings for the repo
I also removed the explicit token for lock-threads as this is now default since 2.1.0 https://github.com/dessant/lock-threads/blob/master/CHANGELOG.md#210-2021-07-09 and did the same for the stale action: https://github.com/actions/stale#repo-token
More about GitHub token permissions: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
=> github: declare permissions for all GitHub Actions

internal/langserver/handlers/semantic_tokens_test.go, internal/lsp/token_encoder.go, internal/lsp/token_types.go
Closes #710
The (LSP) modifier `defaultLibrary` better represents the meaning of dependent labels or attributes, as opposed to `modification` which was chosen mostly arbitrarily as part of the initial implementation in https://github.com/hashicorp/terraform-ls/pull/331
Highlighting dependent labels was already possible prior to this patch but the change of the modifier here reflects the commitment to support custom themes in a more sensible (and hopefully stable) way.
Default VSCode themes [do not assign meaning to any modifiers](https://github.com/microsoft/vscode/blob/main/src/vs/platform/theme/common/tokenClassificationRegistry.ts#L572-L594) but it is possible to take advantage of this in a custom theme or simply by modifying the VSCode settings such as
```json …
```
=> internal/lsp: report dependent modifiers as `defaultLibrary`

internal/scheduler/scheduler_test.go, internal/state/errors.go, internal/state/jobs.go
There is a relatively rare case of when we may end up processing the same job twice here:
https://github.com/hashicorp/terraform-ls/blob/bff4e90811f3375c029cf099142adbf869c56f5c/internal/state/jobs.go#L188-L211
1. a job e.g. ID 42 is found by e.g. "closed scheduler" (`*`)
2. in the split second between finding this job and marking it as running (which itself _is_ correctly guarded by an internal memdb mutex), the involved directory is open.
3. the same job ID 42 is then also found by "open scheduler" (`**`)
4. whichever scheduler obtains the memdb mutex first marks that job as running
5. the other scheduler then waits for the mutex and attempts to do the same
6. because that fails, we return error, making the scheduler to effectively shut down, practically causing a deadlock in places …
=> internal/state: avoid deadlock caused by mid-flight job change

go.mod, go.sum, internal/langserver/handlers/semantic_tokens_test.go, internal/lsp/token_encoder.go, internal/lsp/token_encoder_test.go, internal/lsp/token_types.go
Closes #816
--- 
It is possible that we may want to replace the two tokens with something even more accurate, like `TokenTypeString`, `TokenTypeNumber`, `TokenTypeSet`, `TokenTypeList` etc. but it is currently unclear whether anyone would actually benefit from that. We can always revisit supported tokens later.
We can also see that the VSCode grammar highlights types as variables. I would say that keyword scope is more appropriate, as that leaves variable scope for HCL traversals and allows us to visually distinguish the two. i.e. We can adjust the highlighting of primitive types like `string`, `number`, `null` or `bool` in the grammar as well.
=> internal/lsp: recognize type declarations as semantic tokens

docs/commands.md
Forgot to do this in https://github.com/hashicorp/terraform-ls/pull/846
=> docs: remove `rootmodule` cmd from docs

go.mod, go.sum, internal/decoder/module_schema.go, internal/state/module.go
This PR adds a `Files` attribute to `ModuleMetadata` to complement the changes in https://github.com/hashicorp/terraform-schema/pull/101. With the changes to the earlydecoder we now keep a list of files inside a module.
Depends on https://github.com/hashicorp/terraform-schema/pull/101
Depends on https://github.com/hashicorp/hcl-lang/pull/112
Closes https://github.com/hashicorp/terraform-ls/issues/558
=> Add files to ModuleMetadata

internal/state/documents.go, internal/state/documents_test.go, internal/state/jobs.go, internal/state/state.go
Previously if a nested directory/module was opened, kept open, and a parent directory was then opened, that parent directory would fail to load, resulting in `file not found` errors in the log and causing all IntelliSense for the parent to not be available.
The bug was introduced as part of https://github.com/hashicorp/terraform-ls/pull/771 (i.e. affects 0.26.0+)
=> fix: Ensure loading of parent directory after lower level directories works

.github/workflows/milestone-closed.yml
Since version 2.20.0 of the official extension (released more than a month ago), it no longer updates LS separately but instead LS is bundled within, therefore this PR updates the message accordingly.
=> github: Update message for milestone closure

internal/schemas/gen/gen.go
This is to address the fact delphix-integrations/delphix only has pre-releases at the moment, resulting in `init` failures:
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
delphix-integrations/delphix: no available releases match the given
constraints 
```
=> schemas/gen: exclude delphix-integrations/delphix

docs/SETTINGS.md, internal/langserver/handlers/did_open.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/settings/settings.go
This PR enables single file support by skipping configuring the file watcher with information about what folders to watch. This leaves the watcher with little environment information, but still provides enough functionality to edit a single file. This suits the common transitory workflows for single files. For example, opening a file just to review contents or to make a few line changes without needing the context from an entire Terraform project.
A warning is shown to the user when a single file is opened, explaining that some capabilities may be reduced when editing a single file, and to open a directory to regain full editor functionality. This is to warn the user that while we enable this workflow, we don't encourage it because of the tradeoffs we currently have to do. This warning …
=> Enable opening a single Terraform file

.github/gobenchdata-checks.yml
This is to address the recent nightly failures:
```json
{
"Status": "fail",
"Diffs": [
{
"Status": "fail",
"Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers",
"Benchmark": "BenchmarkInitializeFolder_basic/google-network-2",
"Value": 2622.730844
}
],
"Thresholds": {
"Min": 1430,
"Max": 2470
}
}
```
https://github.com/hashicorp/terraform-ls/runs/5879240603?check_suite_focus=true#step:9:1
```json
{
"Status": "fail",
"Diffs": [
{
"Status": "fail",
"Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers",
"Benchmark": "BenchmarkInitializeFolder_basic/aws-eks-2",
"Value": 2874.628341
}
],
"Thresholds": {
"Min": 1570,
"Max": 2500
}
}
```
https://github.com/hashicorp/terraform-ls/runs/5965803013?check_suite_focus=true#step:9:1
=> ci: bump google-network & awk-eks benchmark thresholds

.github/gobenchdata-checks.yml
This is to address the following nightly failure:
https://github.com/hashicorp/terraform-ls/runs/5983427527?check_suite_focus=true#step:9:1
```json
{
"Status": "fail",
"Diffs": [
{
"Status": "fail",
"Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers",
"Benchmark": "BenchmarkInitializeFolder_basic/k8s-metrics-server-2",
"Value": 1057.225971
}
],
"Thresholds": {
"Min": 1060,
"Max": 2800
}
}
```
=> ci: reduce min threshold for k8s-metrics-server benchmark

internal/schemas/gen/gen.go
Looks like that provider was published but artifacts remain unavailable because the repo is private
```
Error while installing harness/harness-platform v0.0.4: could not query
provider registry for registry.terraform.io/harness/harness-platform: failed
to retrieve authentication checksums for provider: 404 Not Found
```
=> schemas: Exclude harness/harness-platform from embedding

internal/hcl/diff.go, internal/hcl/diff_test.go, internal/langserver/handlers/formatting_test.go
Fixes #793
The diff may be confusing to understand but here's another representation of it, confirming the upstream library works pretty much as expected:
```diff
--- test.tf
+++ test.tf
@@ -1,8 +1,8 @@
resource "aws_lambda_function" "f" {
-    environment {
-        variables = {
-            a = "b"
-        }
+  environment {
+    variables = {
+      a = "b"
}
+  }
}
```
Perhaps the algorithm could have joined the two hunks into one, but the result would be pretty much the same.
=> Fix corrupted diffs in formatting responses

internal/langserver/handlers/command/module_calls.go, internal/langserver/handlers/command/module_calls_test.go, internal/terraform/datadir/module_types.go
With the release of [Terraform 1.1.0](https://github.com/hashicorp/terraform/blob/v1.1/CHANGELOG.md#110-december-08-2021) module source addresses are now stored normalized:
> config: Terraform now checks the syntax of and normalizes module source addresses (the source argument in module blocks) during configuration decoding rather than only at module installation time. This is largely just an internal refactoring, but a visible benefit of this change is that the terraform init messages about module downloading will now show the canonical module package address Terraform is downloading from, after interpreting the special shorthands for common cases like GitHub URLs. (https://github.com/hashicorp/terraform/issues/28854)
---
With this change it's not possible anymore to identify remote …
=> Fix module calls command for remote modules

.github/gobenchdata-checks.yml, .github/workflows/benchmarks.yml
To address some recent failures and cancellations:
```json
{
"Status": "fail",
"Diffs": [
{
"Status": "fail",
"Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers",
"Benchmark": "BenchmarkInitializeFolder_basic/local-single-module-no-provider-2",
"Value": 28.653373
}
],
"Thresholds": {
"Min": 29,
"Max": 55
}
}
```
https://github.com/hashicorp/terraform-ls/runs/6051484898?check_suite_focus=true
https://github.com/hashicorp/terraform-ls/runs/6071802295?check_suite_focus=true
=> ci: adjust benchmarks

.github/gobenchdata-checks.yml
This is to address the following benchmark threshold failures:
```json
{ "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": "BenchmarkInitializeFolder_basic/aws-eks-2", "Value": 2942.189635 } ], "Thresholds": { "Min": 1570, "Max": 2900 } }
{ "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": "BenchmarkInitializeFolder_basic/local-single-module-random-2", "Value": 171.50729 } ], "Thresholds": { "Min": 180, "Max": 300 } }
{ "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": …
```
=> ci: adjust min & max for benchmarks

go.mod, go.sum, internal/terraform/datadir/module_types.go
This PR uses the [latest additions to terraform-registry-address](https://github.com/hashicorp/terraform-registry-address/pull/7) to detect the source of a module.
Related: https://github.com/hashicorp/terraform-ls/pull/872
=> Use terraform-registry-address for parsing module sources

go.mod, go.sum, internal/state/module.go
Depends on 
* https://github.com/hashicorp/hcl-lang/pull/115
* https://github.com/hashicorp/terraform-schema/pull/103
This PR populates the version field for `ModuleCall` and pulls in the latest `terraform-schema` and `hcl-lang` changes.
All this enables linking the source attribute for remote modules to the documentation.
=> Add version to module calls

internal/schemas/gen/gen.go
Looks like they accidentally republished their 2.0.0 version.
```
Error while installing logicmonitor/logicmonitor v2.0.0: checksum list has unexpected SHA-256 hash
797cc1ddcf904a87652a4eb9f3eb3fb515ecdf5da870adae2e81c9f925462116 (expected
9b251be98d9c819321930466a7e5b0d68ade3579925d18e84a55d3a17f2795f4)
```
=> schemas: Exclude logicmonitor/logicmonitor from embedding

.github/workflows/benchmarks.yml
It was not intended that this command outputs to stderr by default, and the behaviour will be removed in the future: https://github.com/bobheadxi/gobenchdata/pull/53
=> benchmarks: use --json instead of piping to results

.github/workflows/benchmarks.yml, results.json
As suggested in https://github.com/hashicorp/terraform-ls/pull/840#discussion_r859404814
```
{ "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": "BenchmarkInitializeFolder_basic/aws-consul-2", "Value": 2128.919215 } ], "Thresholds": { "Min": 1360, "Max": 2100 } } { "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": "BenchmarkInitializeFolder_basic/aws-eks-2", "Value": 3130.552208 } ], "Thresholds": { "Min": 1570, "Max": 3000 } } { "Status": "fail", "Diffs": [ { "Status": "fail", "Package": "github.com/hashicorp/terraform-ls/internal/langserver/handlers", "Benchmark": "BenchmarkInitializeFolder_basic/aws-vpc-2", …
```
=> ci: Output benchmark results as markdown table

go.mod, go.sum, internal/decoder/module_schema.go, internal/decoder/path_reader.go, internal/state/module.go, internal/state/state.go, internal/terraform/module/watcher.go
Depends on:
* https://github.com/hashicorp/terraform-schema/pull/106
* https://github.com/hashicorp/terraform-schema/pull/109
This PR makes use of the new early decoded module calls introduced in https://github.com/hashicorp/terraform-schema/pull/106. We save those in `state.ModuleMetadata` and use them only in `ModuleStore.ModuleCalls()` for now.
Since `ModuleStore.ModuleCalls()` is only used within the watcher, which then requires access to the `moduleCall.Path`, the early decoded modules don't do much, since they're missing the path. But the upcoming features will make better use of that.
Closes https://github.com/hashicorp/terraform-ls/issues/882
=> Decode module calls (for uninitialized modules)

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
Onboard project to the Releases API.
***Note: RelEng  will merge this PR when ready***
=> Onboard to RelAPI

.github/workflows/benchmarks.yml
This was unfortunately missed in https://github.com/hashicorp/terraform-ls/pull/907
The nightly run failed because of that:
https://github.com/hashicorp/terraform-ls/runs/6363134590?check_suite_focus=true#step:9:8
```
/home/runner/work/_temp/e2222aa7-0e94-4603-a77a-a82f434cd9bf.sh: line 3: gobenchdata: command not found
Error: Process completed with exit code 127.
```
=> ci: fix reference to gobenchdata

internal/decoder/decoder.go, internal/langserver/handlers/command/docs_url.go, internal/langserver/handlers/command/handler.go, internal/langserver/handlers/command/module_calls.go, internal/langserver/handlers/command/module_calls_test.go, internal/langserver/handlers/command/module_providers.go, internal/langserver/handlers/execute_command.go, internal/langserver/handlers/execute_command_module_providers_test.go, internal/langserver/handlers/service.go, internal/utm/utm.go
Closes https://github.com/hashicorp/terraform-ls/issues/911
```
2022/05/20 12:41:18 rpc_logger.go:29: Incoming request for "workspace/executeCommand" (ID 15): {"command":"terraform-ls.module.providers","arguments":["uri=file:///private/var/workspace/tf-test"]}
2022/05/20 12:41:18 rpc_logger.go:50: Response to "workspace/executeCommand" (ID 15): {"v":0,"provider_requirements":{"registry.terraform.io/hashicorp/aws":{"display_name":"hashicorp/aws","docs_link":"https://registry.terraform.io/providers/hashicorp/aws/latest"}},"installed_providers":{"registry.terraform.io/hashicorp/aws":"4.14.0"}}
```
```
2022/05/20 12:41:18 rpc_logger.go:29: Incoming request for "workspace/executeCommand" (ID 16): {"command":"terraform-ls.module.calls","arguments":["uri=file:///private/var/workspace/tf-test"]} …
```
=> Add utm parameters to `module.*` commands

internal/langserver/handlers/did_change_watched_files.go, internal/langserver/handlers/did_change_watched_files_test.go, internal/langserver/handlers/did_change_workspace_folders.go, internal/langserver/handlers/service.go
=> internal/service: add support for didChangeWatchedFiles

internal/langserver/handlers/did_change.go
Fixes #310
Related to
- https://github.com/sublimelsp/LSP/issues/1470
- https://github.com/neovim/neovim/issues/18734
- https://github.com/hashicorp/terraform-ls/issues/927
- https://github.com/hashicorp/terraform-ls/issues/936
=> langserver: ignore duplicate document versions in textDocument/didChange

.github/gobenchdata-checks.yml
This is based on recent nightly failures:
- https://github.com/hashicorp/terraform-ls/runs/6701857035?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/6735600392?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/6742423277?check_suite_focus=true
- https://github.com/hashicorp/terraform-ls/runs/6749592449?check_suite_focus=true
=> ci: update benchmark thresholds

.goreleaser.yml
We can publish homebrew formulas via internal tooling, which also better fits into the new release pipeline. We already send the SNS notification which has the ability to trigger the publishing.
See also https://github.com/hashicorp/homebrew-tap/pull/174
This also avoids the need for the release tooling to ignore `*.rb` files as release artifacts in `dist` folder, which currently cause release failures.
=> goreleaser: Remove brew publishing

version.go
This allows us - or more importantly anyone other than us - to set build metadata when building LS.
In particular this allows us to update the community Homebrew formula to help more easily distinguish LS installed from the Homebrew community tap from our own builds - which can be useful when troubleshooting - see e.g. https://github.com/hashicorp/terraform-ls/issues/944#issuecomment-1151095285
https://github.com/Homebrew/homebrew-core/blob/dc4bba37bc14ca0a7796656638d6f4df86cc3e0d/Formula/oras.rb#L21-L25
```sh
go build -ldflags="-s -w -X main.version=0.1.0 -X main.versionMeta=homebrew"
```
```sh
./terraform-ls version
0.1.0-dev+homebrew
platform: darwin/arm64
go: go1.18.2
compiler: gc
```
```
./terraform-ls version -json
```
```json
{
"version": "0.1.0-dev+homebrew",
"go": "go1.18.2", …
```
=> main: allow version metadata to be set

internal/langserver/handlers/command/module_providers.go
=> handlers/command: Return partially parsed metadata from `module.providers`

internal/langserver/handlers/code_action.go, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/initialize.go, internal/protocol/gen/gen.go, internal/protocol/protocol.go
There is no particular motivation behind this bump, other than to keep files up-to-date and avoid surprises when more changes accumulate.
Hopefully next time we have to touch this, the structs are properly importable and generated from the [JSON data models](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#metaModel), so we no longer have to copy them out of gopls, which generates them from TypeScript. 🙈
=> deps: bump LSP structs to gopls 0.8.4

.github/gobenchdata-checks.yml
The code under benchmark recently performed faster than expected:
https://github.com/hashicorp/terraform-ls/runs/7016438173?check_suite_focus=true#step:9:16
I also (re)formatted the YAML file.
=> ci: reduce benchmark minimum threshold for GKE module

internal/langserver/handlers/did_change_workspace_folders.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/initialize.go
The language server isn't able to do anything with invalid/unsupported URIs, such as the ones listed in https://github.com/hashicorp/vscode-terraform/issues/1159
There's a broader question of whether these URIs should even be send to LS. Given that the known majority of such URIs come from VS Code, I created a separate ticket https://github.com/hashicorp/vscode-terraform/issues/1159 to discuss the problem there.
Prior to this patch it would crash when encountered such a URI during `initialize`, `textDocument/didOpen` or `workspace/didChangeWorkspaceFolders`, as reported in https://github.com/hashicorp/terraform-ls/issues/959
We already handle this gracefully in custom commands:
https://github.com/hashicorp/terraform-ls/blob/000cb538ca2325e8e7f7c8d1da86b3ea411942ba/internal/langserver/handl …
=> fix: avoid crash on invalid URIs

internal/langserver/handlers/command/validate.go, internal/langserver/handlers/hooks_module.go, internal/terraform/ast/ast_test.go, internal/terraform/ast/module.go, internal/terraform/ast/variables.go, internal/terraform/parser/module_test.go
Closes https://github.com/hashicorp/terraform-ls/issues/972
Depends on https://github.com/hashicorp/terraform-ls/pull/968
--- 
I label this as enhancement, since Terraform itself doesn't really load hidden files. We can however be more pragmatic about this and still provide some IntelliSense within. The only thing we do _not_ provide is diagnostics, see more on that in https://github.com/hashicorp/terraform-ls/issues/970
=> Provide basic IntelliSense (except for diagnostics) for hidden `*.tf` files

internal/indexer/document_change.go, internal/indexer/indexer.go, internal/indexer/module_calls.go, internal/indexer/walker.go, internal/indexer/watcher.go, internal/job/job.go, internal/job/job_store.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/state/jobs_test.go, internal/walker/walker_collector.go
As per individual commits messages, this PR aims to add error handling where it was missing to ensure that errors are collected and logged + we can also fail tests if errors occur.
From end-user perspective this is intended to be no-op.
=> indexer: refactor & improve/cleanup error handling

go.mod, go.sum
Depends on https://github.com/hashicorp/terraform-ls/pull/987
---
Brings in https://github.com/hashicorp/terraform-schema/pull/121 and https://github.com/hashicorp/terraform-schema/pull/123
=> deps: bump terraform-schema to 408b2ae

docs/SETTINGS.md, internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/settings/settings.go, internal/settings/settings_test.go, internal/walker/walker.go
Closes https://github.com/hashicorp/terraform-ls/issues/704
=> settings: repurpose indexer-related options

internal/langserver/handlers/initialize.go, internal/settings/settings.go
This is just a small addition to #1003 to make the warning clearer.
=> settings: decode deprecated ignoreDirectoryNames & warn

docs/SETTINGS.md, docs/language-clients.md, internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/settings/settings.go, internal/settings/settings_test.go
As per our internal conversation yesterday, this allows us to get best of both worlds where VS Code can present nice settings UI and LS isn't limited to a flat structure.
I will raise a **separate PR** to update all three `terraform*` options to follow the same principles as documented and further align it with https://github.com/hashicorp/vscode-terraform/blob/main/docs/settings-migration.md , i.e.
instead of
```json
{
"terraformExecPath": "",
"terraformExecTimeout": "",
"terraformExecLogFilePath": ""
}
```
we will accept
```json
{
"terraform": {
"path": ""
"timeout": ""
"logFilePath": ""
}
}
```
and any future (stable, non-experimental) settings can follow these principles.
=> settings: break down indexing options

internal/schemas/gen/gen.go
This is to help maintainers in local dev environments, where we may be using M1 Mac. Prior to this patch, generating schemas would fail as many providers don't provide builds for darwin/arm64.
For context I started this patch as I was trying to reproduce and debug these weird failures:
https://github.com/hashicorp/terraform-ls/runs/7467545895?check_suite_focus=true#step:6:43
```
Error: Failed to install provider
Error while installing bluecatlabs/bluecat v1.0.0: local error: tls: bad
record MAC
Error: Failed to install provider
Error while installing dome9/dome9 v1.27.1: local error: tls: bad record MAC
Error: Failed to install provider
Error while installing vmware/avi v22.1.1: local error: tls: bad record MAC
Error: Failed to install provider
Error while installing …
```
=> schemas: Improve logging & ignoring when generating schemas

docs/SETTINGS.md, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/settings/settings.go, internal/settings/settings_test.go
~Depends on https://github.com/hashicorp/terraform-ls/pull/1010~
This aligns Terraform CLI related settings with the recently documented principles https://github.com/hashicorp/terraform-ls/blob/main/docs/language-clients.md#configuration
=> settings: break down terraform CLI related settings

internal/cmd/serve_command.go, internal/langserver/handlers/service.go
Depends on:
- https://github.com/hashicorp/terraform-ls/pull/1010
- https://github.com/hashicorp/terraform-ls/pull/1011
--- 
These CLI flags were deprecated almost a year ago as part of https://github.com/hashicorp/terraform-ls/blob/main/CHANGELOG.md#0210-23-august-2021 so it's about time to just remove them.
=> cmd/serve: Remove deprecated `-tf-exec-*` CLI flags

docs/USAGE.md
Update usage doc supported filetypes and neovim docs with lua specific configuration. If there is anything I should add and/or change please let me know. 
Fixes #660
=> Update usage doc supported filetypes and neovim docs

internal/schemas/gen/gen.go
The latest release 2.4.5 is missing on GitHub, https://github.com/hashicorp/terraform-ls/runs/7615086797?check_suite_focus=true
=> Schemas: Exclude nttcom/ecl

go.mod, go.sum, internal/decoder/decoder.go, internal/hooks/hooks.go, internal/hooks/module_source_local.go, internal/langserver/handlers/complete.go, internal/langserver/handlers/completion_hooks.go, internal/langserver/handlers/completion_resolve.go, internal/langserver/handlers/completion_resolve_test.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/lsp/completion.go, internal/lsp/text_edits.go, internal/protocol/completion.go, internal/terraform/module/module_ops.go
This PR introduces a new `hooks` package, which we can use to implement hooks for dynamic completion. Hooks will be implemented as part of https://github.com/hashicorp/vscode-terraform/issues/672.
We also introduce a new `completionItem/resolve` handler, which editors can use to update a completion item with more detailed data. The data is obtained via the execution of a resolve hook.
---
* Closes https://github.com/hashicorp/terraform-ls/issues/868
* Requires https://github.com/hashicorp/hcl-lang/pull/123
=> Add hooks for dynamic completion

internal/schemas/gen/gen.go
This is to help avoid any doubts as to where the Terraform installation comes from.
In our case we seem to rely on Terraform installed in GHA environment, for better or worse and this is to make that fact more obvious.
=> schemas: log exec path to Terraform

docs/commands.md, internal/langserver/handlers/command/terraform.go, internal/langserver/handlers/execute_command.go, internal/langserver/handlers/execute_command_terraform_version_test.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/protocol/experimental.go
This commit adds a new `module.terraform` command which returns the required and discovered version of Terraform in the currrent workspace.
=> Add terraform version command

internal/indexer/document_change.go, internal/indexer/module_calls.go, internal/indexer/walker.go, internal/indexer/watcher.go, internal/job/job.go, internal/scheduler/scheduler_test.go, internal/state/job_id_slice_index.go, internal/state/jobs.go, internal/state/jobs_test.go, internal/state/module.go, internal/state/slice_length_index.go, internal/state/state.go, internal/walker/walker.go
Prior to this PR, the only way we could chain jobs was via `Defer`. This had one unfortunate limit, which is that a job can only depend on exactly one other job, i.e. there was just 1-to-1 dependency.
As part of introducing a new job type for parsing provider versions in https://github.com/hashicorp/terraform-ls/pull/1014 it became clear that the new job will need to rely on 2+ other jobs:
- parsed files
- decoded metadata (via earlydecoder) - so that we have `required_providers`
- parsed module manifest (+ any/all modules decoded) - so that we have `required_providers` of any submodules
I originally attempted to solve it in a hacky way by introducing `WaitForJobs()` inside `Defer`, but that created a few other problems - need to run at least two go routines, so that one can be blocked …
=> state: Introduce `DependsOn` for N-to-1 job dependencies

internal/indexer/walker.go, internal/indexer/watcher.go, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/did_change_watched_files_test.go, internal/langserver/handlers/document_link_test.go, internal/langserver/handlers/execute_command_module_providers_test.go, internal/langserver/handlers/go_to_ref_target_test.go, internal/langserver/handlers/testdata/single-fake-provider/main.tf, internal/state/module.go, internal/state/module_test.go, internal/state/provider_schema.go, internal/state/provider_schema_test.go, internal/state/state.go, internal/terraform/datadir/module_manifest.go, internal/terraform/datadir/paths.go, internal/terraform/datadir/plugin_lock_file.go, internal/terraform/datadir/plugin_lock_file_test.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go, internal/walker/walker_test.go
Depends on https://github.com/hashicorp/terraform-ls/pull/1021 (`DependsOn`)
Closes https://github.com/hashicorp/terraform-ls/issues/992
--- 
This introduces `ParsePluginVersions` which can parse provider/plugin versions as encoded by any version from Terraform v0.12. Attached tests probably best explain the differences between the versions.
Secondly the PR introduces `ParseProviderVersions` job, which leverages the mentioned function to parse the versions. This becomes the only way we obtain provider versions (previously it was `terraform version -json` as part of `GetTerraformVersion` job).
Lastly I raised https://github.com/hashicorp/terraform-ls/issues/1025 to further explain and eventually address the problem with path separators. With `testing/fstest` (or at least for the `ReadDir` …
=> Parse provider versions from lock file before obtaining schema

go.mod, go.sum
This is to bring in https://github.com/hashicorp/terraform-schema/pull/130
Fixes https://github.com/hashicorp/terraform-ls/issues/1026
=> fix: bump terraform-schema to fix crash on invalid provider name

go.mod, go.sum, internal/decoder/module_schema.go, internal/indexer/document_open.go, internal/indexer/walker.go, internal/indexer/watcher.go, internal/langserver/handlers/code_action_test.go, internal/langserver/handlers/code_lens_test.go, internal/langserver/handlers/complete_test.go, internal/langserver/handlers/did_change_test.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/did_open_test.go, internal/langserver/handlers/document_link_test.go, internal/langserver/handlers/execute_command_init_test.go, internal/langserver/handlers/execute_command_module_callers_test.go, internal/langserver/handlers/execute_command_module_providers_test.go, internal/langserver/handlers/execute_command_modules_test.go, internal/langserver/handlers/execute_command_test.go, internal/langserver/handlers/execute_command_validate_test.go, internal/langserver/handlers/formatting_test.go, internal/langserver/handlers/go_to_ref_target_test.go, internal/langserver/handlers/handlers_test.go, internal/langserver/handlers/hover_test.go, internal/langserver/handlers/references_test.go, internal/langserver/handlers/semantic_tokens_test.go, internal/langserver/handlers/service.go, internal/langserver/handlers/symbols_test.go, internal/langserver/handlers/workspace_symbol_test.go, internal/state/jobs.go
Depends on https://github.com/hashicorp/terraform-schema/pull/129
Closes https://github.com/hashicorp/terraform-ls/issues/993
While the primary motivation behind the change was performance, it brings a minor UX impact.
**Before**: No IntelliSense available, most schema-dependent jobs providing data for IntelliSense fail, as per [errors in log](https://gist.github.com/radeksimko/0fb6825951bb316deef9ed4b43b306b5).
**After**: 0.12-based IntelliSense provided, no errors in log.
--- 
The UX for too new version (e.g. 1.5.0) and for when the version is not known (yet) remains practically the same, it is just hopefully more obvious from the changed code combined with the upstream tfschema changes.
=> Pick core schema only based on `required_version` constraint

.github/gobenchdata-checks.yml, .github/workflows/benchmarks.yml, internal/indexer/document_change.go, internal/indexer/document_open.go, internal/indexer/module_calls.go, internal/indexer/walker.go, internal/indexer/watcher.go, internal/job/ignore_state.go, internal/job/job.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/state/jobs.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go
Closes #1002
Depends on #1027
--- 
The removal of de-duplication upon job enqueuing is necessary to avoid various bugs and race conditions where we'd deduplicate jobs which appear to be same, but have different `Defer` or `DependsOn`, i.e. we'd be overly aggressive in the deduplication efforts.
It is worth clarifying here that this PR doesn't affect jobs which run as part of text synchronization - i.e. `textDocument/didOpen`, `textDocument/didChange` or `workspace/didChangeWatchedFiles`. It only aims to reduce the duplicated work as part of the walker (which is triggered by `initialize`), which would occur if the user has deep workspace which takes a while to index via walker, and opens a few (yet unindexed) modules, which get indexed as a priority.
For `textDocument/didChange` and …
=> indexer/walker: Avoid running jobs where not needed

internal/langserver/handlers/code_action.go, internal/langserver/handlers/formatting.go
From past experience this is a common source of bug reports, for various reasons - often due to https://github.com/tfutils/tfenv/issues/196 which was now resolved, but it seems reasonable to me to log the execution time as it's a commonly used feature, so it's effectively a hot path.
This allows us to rule out TF CLI as a cause, if/when people report performance related issues.
=> textDocument/formatting: log terraform fmt execution time

.github/workflows/release.yml, .goreleaser.yml, algolia.go, go.mod, go.sum, internal/algolia/algolia.go, internal/cmd/serve_command.go, internal/context/context.go, internal/hooks/hooks.go, internal/hooks/module_source_local.go, internal/hooks/module_source_local_test.go, internal/hooks/module_source_registry.go, internal/hooks/module_source_registry_test.go, internal/hooks/module_version.go, internal/hooks/module_version_test.go, internal/langserver/handlers/completion_hooks.go, internal/lsp/completion.go, internal/registry/registry.go, internal/registry/registry_test.go, internal/state/module.go, main.go
Closes https://github.com/hashicorp/vscode-terraform/issues/672
--- 
This PR adds three hooks for completing module `source` and `version`.
Uses the local indexed modules and offers relative path suggestions, when completing module sources.
Searches the Terraform registry modules via Algolia and fetches the full source address and module description.
For this to work, we now need to pass `main.algoliaAppID` and `main.algoliaAPIKey` via `ldflags` on build.
Fetches the available module versions from the Terraform registry.
Completion of required inputs was moved to #1029
=> Complete module `source` and `version`

.goreleaser.yml
This is to avoid some CPU/time waste on running tests twice on every PR/push, which we generally always do as per our current GHA workflow setup.
https://github.com/hashicorp/terraform-ls/blob/4459e5ccae15ae64da61118cece2a1c1aa0cff10/.github/workflows/ci.yml#L3-L9
It does mean we'd no longer run tests as part of a release pipeline, but I'm not sure that was ever that much valuable anyway since we'd usually wait for the last `main` push CI workflow to turn green.
I'm also removing an old ENV variable `GO111MODULE` which is no longer relevant in the Go version we use.
=> clean/ci: avoid running tests via GoReleaser & remove GO111MODULE

internal/langserver/session/session.go
Popped up in an error message I received in #1041, thought it worth a quick PR to fix.
=> Spelling: initalized -> initialized

docs/USAGE.md
Not every reader may be familiar with the vim plugin system and I _think_ the linked post explains it quite well, in fact better than the [official manual](https://github.com/vim/vim/blob/03c3bd9fd094c1aede2e8fe3ad8fd25b9f033053/runtime/doc/repeat.txt#L515), but I may be biased as a non-seasoned vim user. 🤷🏻‍♂️
=> docs: Add link to post explaining vim plugin installation

.goreleaser.yml
I noticed as part of https://github.com/hashicorp/terraform-ls/issues/1041 that we released `0.29.0` (stable) as `0.29.0-dev`, which is because https://github.com/hashicorp/terraform-ls/pull/945 didn't follow a corresponding update of the GoReleaser config.
This PR fixes that.
```
goreleaser build --snapshot --skip-post-hooks --rm-dist
./dist/signable_darwin_arm64/terraform-ls version
0.29.0-dev
platform: darwin/arm64
go: go1.18.5
compiler: gc
```
```
goreleaser build --snapshot --skip-post-hooks --rm-dist
./dist/signable_darwin_arm64/terraform-ls version
0.29.0-snapshot.dfd43fd
platform: darwin/arm64
go: go1.18.5
compiler: gc
```
=> goreleaser: Use correct ldflag (versionPrerelease) when compiling LS

internal/state/provider_schema.go, internal/state/provider_schema_test.go
This PR fixes the LS panic reported in https://github.com/hashicorp/vscode-terraform/issues/1213.
<details><summary>Stack trace:</summary>
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13c4898]
goroutine 38 [running]:
github.com/hashicorp/go-version.prereleaseCheck(0xc09a8067e0, 0x3)
github.com/hashicorp/go-version@v1.6.0/constraint.go:198 +0x18
github.com/hashicorp/go-version.constraintGreaterThanEqual(0xc09a8067e8, 0xc0aa07f858)
github.com/hashicorp/go-version@v1.6.0/constraint.go:250 +0x25
github.com/hashicorp/go-version.(*Constraint).Check(...)
github.com/hashicorp/go-version@v1.6.0/constraint.go:163
github.com/hashicorp/go-version.Constraints.Check({0xc0cb192370, 0x1, 0xc}, 0x170c841) …
```
=> Fix panic on obtaining provider schemas

internal/langserver/handlers/exit_test.go
This PR fixes the flaky exit handler test. The sleep makes sure that we account for the asynchronous nature of LS notifications.
I think using `time.Sleep` isn't the best, but a very pragmatic solution here. 
```
$ go test -timeout 30s -run '^TestExit$' github.com/hashicorp/terraform-ls/internal/langserver/handlers -count=1000
--- FAIL: TestExit (0.00s)
exit_test.go:20: Expected service stop function to be called
--- FAIL: TestExit (0.00s)
exit_test.go:20: Expected service stop function to be called
FAIL
FAIL    github.com/hashicorp/terraform-ls/internal/langserver/handlers  1.807s
FAIL
```
```
$ go test -timeout 30s -run '^TestExit$' github.com/hashicorp/terraform-ls/internal/langserver/handlers -count=1000
ok      github.com/hashicorp/terraform-ls/internal/langserver/handlers  13.512s …
```
=> fix: flaky exit handler test

internal/langserver/handlers/execute_command_terraform_version_test.go, internal/state/module.go, internal/state/module_changes_test.go, internal/state/module_test.go, internal/state/provider_schema.go, internal/state/provider_schema_test.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go
This is a follow-up to a recent bug fix - https://github.com/hashicorp/terraform-ls/pull/1048
The linked PR addressed the fact that we may sometimes get provider schemas with `nil` versions. This PR additionally ensures that versions are in fact stored as they should be and clarifies some related edge cases in attached comments.
The temporary lack of versions for schemas is not as easily noticeable thanks to the loose/optimistic matching of schemas we perform, where even if we don't match the version, we always match based on the address, or even just provider name alone.
The only difference it makes is when there are two schemas for the same provider address of different versions - so that inaccuracy is being addressed.
https://github.com/hashicorp/terraform-ls/blob/0f745e191e738796628db4 …
=> fix: Add missing provider schema versions

.gitignore, internal/hooks/module_source_registry.go, internal/hooks/module_source_registry_test.go
This PR updates the check for local module prefixes from `../` to `.` to stop sending search requests for `.` and `..` to the TF registry.
Closes https://github.com/hashicorp/terraform-ls/issues/1053
=> Don't query the TF registry for module sources starting with "."

.github/gobenchdata-checks.yml, .github/workflows/benchmarks.yml
This is to reflect recent CI failures.
=> ci: bump benchmark thresholds

internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/uri/uri.go, internal/uri/uri_test.go
This adds another piece of logic to attempt to detect UNC WSL Uri as the workspace to open, and return a more informative error so the client can handle prompting the user.
The UNC WSL Uri being passed is in the form of `\\wsl$\Ubuntu\home\james\some\path`. If the user wants to edit files in the WSL instance, they should be opening the workspace in the Remote WSL extension.
When the VS Code sends the path to terraform-ls, it is urlencoded as `\\wsl%24\Ubuntu\home\james\some\path`. This fails `uri.IsURIValid`, which is incorrect because it is a valid path that needs to be decoded. Even if it is decoded, further on in the `uri` package we make assumptions about file paths that ignore the server portion of a UNC path, resulting in terraform-ls attempting to use `Ubuntu\home\james\some\path`. …
=> Handle Invalid WSL URIs

go.mod, go.sum, internal/schemas/gen/gen.go, internal/schemas/schemas_preloadschema.go
Closes #517 
This represents a minor tech debt cleanup in preparation for https://github.com/hashicorp/terraform-ls/issues/990
=> schemas/cleanup: replace vsfsgen w/ Go stdlib's embed

internal/indexer/document_change.go, internal/indexer/module_calls.go, internal/indexer/walker.go, internal/schemas/schemas.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go
This was discovered as part of recent failing benchmarks, although it isn't direct root cause of the fail:
https://github.com/hashicorp/terraform-ls/actions/runs/3187102652/jobs/5198346112
=> schemas: Treat legacy providers as hashicorp or builtin

.github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/release.yml
This PR updates our workflows to make `setup-go` obtain the Go version directly from the `.go-version` file.
=> Update `setup-go` to obtain version via `go-version-file`

.github/workflows/nightly-tests.yml, internal/scheduler/scheduler_long_test.go, internal/state/jobs.go
Fixes #1065
I couldn't come up with a more light-weight test which would reproduce the bug. As mentioned in the comment, it (scheduling over 1 million jobs) takes about 3-4 minutes to finish on M1 Pro and consumes decent chunk of almost all cores + ~5-6GB of memory at peak.
The Windows GHA environment runs out of memory before the test can even finish. 🙊 
There are a few options to consider:
1. remove the test entirely (some risk that we re-introduce the bug)
2. gate the test on ENV variable, such as `LONG_TESTS=1`
3. gate the test on build tags, such as `-tags=longtests`
We could also consider not running the test on non-empty `CI` ENV variable (which most CI systems set, incl. GitHub Actions), but I'd argue that it's probably not as valuable to run that test locally for most of the time …
=> state: avoid infinite recursion in JobStore

go.mod, go.sum, internal/decoder/decoder_test.go, internal/schemas/schemas.go
Fixes https://github.com/hashicorp/terraform-ls/issues/1080
Depends on https://github.com/hashicorp/terraform-schema/pull/149
=> decoder: fix race condition in terraform-schema SchemaMerger

internal/schemas/schemas.go
This is to avoid benchmark failures due to inability to parse the output:
https://github.com/hashicorp/terraform-ls/actions/runs/3286664100/jobs/5415008036#step:6:1
=> schemas: remove log statements

go.mod, go.sum
This is to bring https://github.com/hashicorp/hcl-lang/pull/144 in
=> deps: bump hcl-lang to `b20d6288c7f3`

go.mod, go.sum
This PR pulls in all the upstream changes to [hcl-lang](https://github.com/hashicorp/hcl-lang/) and [terraform-schema](https://github.com/hashicorp/terraform-schema/).
With the changes, we introduce:
* Support for `self.*` references: https://github.com/hashicorp/hcl-lang/pull/163
* `dynamic` block support, including label and content completion: https://github.com/hashicorp/hcl-lang/pull/154
* Support for `each.*` references: https://github.com/hashicorp/hcl-lang/pull/162
* Support for `count.index` references https://github.com/hashicorp/hcl-lang/pull/160
Closes https://github.com/hashicorp/terraform-ls/issues/1096
Closes https://github.com/hashicorp/terraform-ls/issues/859
Closes https://github.com/hashicorp/terraform-ls/issues/1095
Closes …
=> Enable `for_each`, `count`, `self.*` and `dynamic` support

.github/workflows/ci.yml
[The issue](https://github.com/actions/runner-images/issues/4856), why we pinned the windows version to 2019 should be resolve by now. Let's bump this to latest.
=> ci: Bump `windows-2019` to `windows-latest`

.github/workflows/release.yml
This PR updates the action version to the Node 16 based one. It will get rid of two pipeline warnings.
[More information](https://github.com/aws-actions/configure-aws-credentials/issues/521)
=> ci: Bump `aws-actions/configure-aws-credentials` to `v1-node16`

.github/workflows/release.yml
This should get rid of the warning in the [`Install hc-codesign` step](https://github.com/hashicorp/terraform-ls/actions/runs/3542571029/jobs/5948212728#step:6:32).
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Replace deprecated set-output with new `$GITHUB_OUTPUT` var

.github/workflows/benchmarks.yml, .github/workflows/ci.yml, .github/workflows/issue-comment-created.yml, .github/workflows/lock.yml, .github/workflows/milestone-closed.yml, .github/workflows/nightly-tests.yml, .github/workflows/release.yml, .github/workflows/stale.yml
The intention here is to reduce the security risk posed by the supply chain - i.e. externally maintained GitHub Actions.
The expectation is that dependabot will continue to update these hashes as and when new versions become available.
=> github: Pin external GitHub Actions to hashes

docs/USAGE.md
This PR replaces the nvim's deprecated functions with new ones.
You can check for deprecated functions with `:h  deprecated` command on nvim.
```
- vim.lsp.buf.formatting()              Use vim.lsp.buf.format() with
{async = true} instead.
```
nvim docs [here](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()).
=> docs: remove deprecated function & change recommended function

.github/CODEOWNERS
As per our internal discussions, this helps differentiate between engineers on the team who need to be pinged about reviews and anyone else who does not.
=> github: Update CODEOWNERS file

.github/workflows/stale.yml
This PR proposes a few changes to the `stale` GHA workflow, which was effectively unused due to one of the settings set more conservatively.
Specifically, we set `days-before-stale: '-1'` which means that the bot would never attempt to mark issues as stale by itself. That first step was left to us, but I think nobody even realised this is the case and so nobody ever assigned `stale` label to an issue/PR.
With some older issues being accumulated in the repo, I wanted to update the settings, such that we can more proactively tackle the backlog and communicate expectations to the contributors/reporters.
- all automation remains scoped to just issues labelled `waiting-response`
- bot will automatically label an issue/PR as `stale` after 30 days of no response and comment with an updated …
=> github: Adjust settings of the stale workflow

version.go
This is useful e.g. when VERSION file is edited via GitHub UI, which automatically adds a trailing newline.
=> version: trim spaces from raw `VERSION`

.github/CONTRIBUTING.md
This is to aid clarity and enable any maintainer to cut releases easily.
=> CONTRIBUTING.md: Add release guide

internal/terraform/parser/module.go, internal/terraform/parser/module_test.go, internal/terraform/parser/testdata/invalid-links/invalid.tf, internal/terraform/parser/testdata/invalid-links/resources.tf
This PR changes the parsing of module files so that if we encounter an inaccessible file, we continue parsing all the other module files instead of aborting with an error.
That should improve the experience for emacs users, relying on magic symlinks to keep track of open files.
Fixes https://github.com/hashicorp/terraform-ls/issues/1067
**Before**
No features available within the module
**After**
=> Continue parsing module files on error

go.mod, go.sum
This is to bring in https://github.com/hashicorp/terraform-schema/pull/184 which in turn enables correct parsing of default values in optional object attributes, such as in the following sample config:
```hcl
variable "example" {
type = object({
foo = optional(string, "toot") # HERE
bar = number
})
}
```
This is a minor enhancement in the sense that we're catching up behind Terraform 1.3 which introduced defaults, as per https://github.com/hashicorp/terraform-ls/issues/917 (https://github.com/hashicorp/terraform/pull/31154).
=> deps: bump terraform-schema to `62b1929`

.github/workflows/build.yml
When migrating to CRT, I missed disabling cgo for native (Linux) builds. We had this set before in the [`.goreleaser.yml`](https://github.com/hashicorp/terraform-ls/blob/f3eb1948a92f9b308fc33f8a665f13cece024979/.goreleaser.yml#L1-L2)
The current binaries released for Linux are dynamically linked, as reported in https://github.com/hashicorp/vscode-terraform/issues/1346
=> Disable cgo for builds

go.mod, go.sum, internal/langserver/handlers/command/init.go, internal/langserver/handlers/command/module_callers.go, internal/langserver/handlers/command/module_calls.go, internal/langserver/handlers/command/module_providers.go, internal/langserver/handlers/command/terraform.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/execute_command.go, internal/langserver/handlers/execute_command_init_test.go, internal/langserver/handlers/execute_command_module_callers_test.go, internal/langserver/handlers/execute_command_module_providers_test.go, internal/langserver/handlers/execute_command_modules_test.go, internal/langserver/handlers/execute_command_test.go, internal/langserver/handlers/execute_command_validate_test.go, internal/langserver/handlers/formatting_test.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/initialize_test.go, internal/langserver/handlers/semantic_tokens.go, internal/langserver/handlers/service.go, internal/langserver/handlers/shutdown_test.go, internal/langserver/session/errors.go
In preparation for tagging a v1 for this module, this release contains some API changes, specifically a package rename. This PR updates the terraform-ls usage. The changes have no semantic effect.
I'm sending this in advance since Dependabot won't be able to handle it automatically, but feel free to take it over if you'd prefer to make the change some other way, skip the update, etc.
(For background see https://github.com/creachadair/jrpc2/issues/46).
=> Update github.com/creachadair/jrpc2 to v0.46.0.

internal/langserver/handlers/hooks_module.go
Previously we would submit an empty backend if the configuration used the default value. This detects an empty value and uses the default "app.terraform.io" value instead.
=> Fix remote backend tracking

internal/registry/module.go, internal/state/module.go, internal/state/registry_modules.go, internal/state/registry_modules_test.go, internal/state/state.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go
This PR introduces caching for registry module HTTP request errors. We're currently only caching 404 errors, but it might also be sensible to cache other errors.
The change dramatically improves the performance when many jobs run in the background after a more significant text change.
**Before**
**After**
=> Cache registry module errors

docs/features.md
This aims to provide a quick overview of (un)supported methods, which in turn could be used as a guide for future planning and may be useful for client maintainers too.
This is similar to lists in other clients or servers, e.g. 
- https://github.com/sublimelsp/LSP/blob/main/docs/src/features.md
- https://github.com/golang/tools/blob/master/gopls/doc/design/design.md#features
- https://github.com/juliosueiras/terraform-lsp#lsp-support-table
We may end up restructuring this and/or making it otherwise a bit more useful for common users, e.g. by adding GIFs and screenshots etc. and by linking to various relevant open issues and describing what exact parts are, will be and won't be implemented. That said I didn't intend this PR to be perfect, but rather a starting point on a path towards …
=> docs: Add matrix with LSP features

.github/workflows/add-copyright-headers.yml, .github/workflows/test.yml
This is a solution we've been trialing on the CDK team and it's working well for us so I figured I'd propose it to this team as well.
Rather than failing a check on PRs if the copyright headers are missing (which is potentially annoying to community contributors who then either have to manually copy-paste the headers or install HashiCorp's copywrite tool), this adds a new commit on any PRs that are missing the headers that adds them in automagically. (If no headers are missing then it does nothing.)
=> Add copyright headers automagically instead of failing a check on PRs

docs/USAGE.md
Related to #1140 
`callback` in `vim.api.nvim_create_autocmd()` seems to require a lambda.
I didn't test it for VimScript or Neovim v0.5.0+ so I didn't change it for these.
=> Change nvim_create_autocmd callback to a lambda

internal/scheduler/scheduler_long_test.go
This was discovered as part of (failing) nightly runs https://github.com/hashicorp/terraform-ls/actions/runs/5703957126/job/15457105405 ever since we merged https://github.com/hashicorp/terraform-ls/pull/1327 which changed some interfaces.
Because the test only runs/compiles with a specific build tag, this wasn't discovered as part of the original PR or through regular PR-based CI jobs.
Here is a test run from the branch: https://github.com/hashicorp/terraform-ls/actions/runs/5712124794/job/15474997813
=> fix: Add missing context argument to a test

internal/indexer/document_change.go
This job may make an HTTP request and we schedule it in the low priority queue so we don't want to wait for it.
This can significantly reduce the request time for the `didOpen` and `didChange` calls.
**Before**
**After**
Another improvement might be not to schedule this job if there are no external module calls in a file.
=> jobs: Don't wait for `GetModuleDataFromRegistry` job

go.mod, go.sum
This is to bring in https://github.com/hashicorp/terraform-schema/pull/238 and reduce the noise in OTEL data.
=> deps: Bump terraform-schema to 8234469

internal/terraform/module/module_ops.go
Follow-up from https://github.com/hashicorp/terraform-ls/pull/1327
Related to https://github.com/hashicorp/terraform-ls/issues/1056
One area identified as consuming significant time when working through some data is the `PreloadEmbeddedSchema` job. While this isn't necessarily an indication of a bottleneck in itself, this PR adds some further instrumentation to help gain further visibility into that job.
**Example dataset:**
=> OTEL: Instrument `PreloadEmbeddedSchema` job

go.mod, go.sum
This is mostly to silence the alert about https://pkg.go.dev/vuln/GO-2023-1988 even though I don't believe the repository is in fact vulnerable as it does not consume the affected sub-package.
=> deps: Bump terraform-schema to 571f93a5dc94

internal/settings/settings.go
Adds `validation.earlyValidation` as a new setting.
I chose to use `validation` as a primary key as we expect to add future settings for this feature.
=> Introduce a new setting for early validation

go.mod, go.sum, internal/decoder/decoder.go, internal/decoder/validations/unreferenced_origin.go, internal/decoder/validations/unreferenced_origin_test.go, internal/indexer/document_change.go, internal/langserver/diagnostics/diagnostics.go, internal/langserver/diagnostics/diagnostics_test.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/hooks_module.go, internal/state/module.go, internal/state/module_changes.go, internal/state/module_test.go, internal/terraform/ast/diagnostics.go, internal/terraform/ast/module.go, internal/terraform/ast/variables.go, internal/terraform/module/module_ops.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This PR updates the way we store and publish diagnostics to allow publishing from a single location (a module hook).
Whereas before we only stored diagnostics from parsing inside the module state, we now store a map instead, which can contain diagnostics from different sources. The map is filled by different jobs, such as parsing or early validation.
We've moved the execution of `terraform validate` into its own job that is scheduled on save (if enabled) to remove the manual publishing of diagnostics in that command. This leaves us with a single place for publishing (a module hook) that is automatically triggered whenever a module's diagnostic map changes.
Resolves #1337
=> Centralize diagnostics publishing

internal/context/context.go, internal/indexer/document_change.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go
Requires #1361
This PR uses the new setting introduced in #1353, to check if the early validation feature is enabled before running any early validation jobs.
=> Check early validation setting before scheduling jobs

internal/state/provider_schema.go, internal/terraform/module/module_ops.go
In https://github.com/hashicorp/terraform-ls/pull/1071, we have changed the way we store and load the bundled schemas to reduce our memory footprint. We released the work with version `0.29.3`. User reports indicate that in previous versions, e.g. `0.29.2`, the observed performance was better.
**TL:DR we read a schema file from disk every time, even if we have already loaded the file**
We schedule the `PreloadEmbeddedSchema` job when decoding a module (`textDocument/didOpen`, `textDocument/didChange`) and from the indexer when walking the workspace files.
The job reads the required providers from a module and checks which schemas are still missing in our internal memory. We use the list of missing schemas to load schemas from disk. After loading a schema from disk, we store it with the …
=> Improve `PreloadEmbeddedSchema` performance

go.mod, go.sum, internal/context/context.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/state/jobs.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/testdata/invalid-config/main.tf, internal/terraform/module/testdata/invalid-config/variables.tf
This PR updates the schema validation job to check if it was scheduled by a `didChange` request. This request is sent by a client when a user edits a file.
If the content of a single file changes, it should not be necessary to re-validate all the files in the module. We can reuse our stored diagnostics for most of the module's files, and re-validate only the file being edited.
To achieve this we introduce a new `RPCContext`, that we attach to all jobs.
=> Only validate a single file on `didChange`

internal/scheduler/scheduler_test.go, internal/state/jobs_test.go, internal/state/module_changes_test.go, internal/walker/walker_test.go
This PR fixes the test failures on `f-early-validation` by adding the `RPCContext` to test files.
=> Add `RPCContext` to job-related tests

internal/langserver/handlers/command/validate.go
I accidentally removed progress reports for `terraform validate` while working on https://github.com/hashicorp/terraform-ls/pull/1361.
This PR adds it back. Although I see no difference in the LS log output
=> Re-add progress reporting for Terraform validate

internal/langserver/handlers/did_change_watched_files.go
Closes #1366
A common use case for `workspace/didChangeWatchedFiles` is to receive updates about files changed _outside_ of the IDE - such as when the user runs `git checkout` to switch branches.
The LSP spec isn't 100% clear about whether clients should always send `workspace/didChangeWatchedFiles` also for open files. A popular language client (VS Code) always does - i.e. we receive both `textDocument/didSave` on save and then subsequently `workspace/didChangeWatchedFiles` even if the file content has not changed - only the modification timestamp has.
This leads us to processing the exact same files (content-wise) multiple times in row (1st on `textDocument/didChange` 2nd and any other time on `workspace/didChangeWatchedFiles` as followed after `textDocument/didSave`), in turn wasting …
=> langserver: Avoid re-processing open files after file saving

go.mod, go.sum
This is to bring in https://github.com/hashicorp/terraform-schema/pull/251 - once merged, we should rebase https://github.com/hashicorp/terraform-ls/pull/1368
I can't think of how this could affect the end users without https://github.com/hashicorp/terraform-schema/pull/251 (in positive or negative way) but it seems better to keep dependency updates in `main` to prevent conflicts in the branch/PR.
=> deps: bump terraform-schema to `90a397096838`

internal/decoder/validations/unreferenced_origin.go, internal/decoder/validations/unreferenced_origin_test.go
While testing https://github.com/hashicorp/terraform-ls/pull/1368 we discovered that validating all "matchable" references means we also end up validating cross-module references, such as module inputs.
This, in combination with the fact that we limit lookups to inside of the single module, leads to false diagnostics, such as shown below:
I'm proposing in this PR to treat module input validation as a _feature_ we can enable later, when we had the time to properly assess the validation feature as a whole, and especially its performance impact and for the time being just avoid validating it.
If agreed/merged, we should probably create an issue to track validation of module inputs (DirectOrigin) and also module sources (PathOrigin).
=> validations: Limit ref. validation to only LocalOrigin(s)

internal/decoder/validations/unreferenced_origin.go, internal/decoder/validations/unreferenced_origin_test.go
This addresses one small part of https://github.com/hashicorp/terraform-ls/issues/1364 - in particular `local.*` reference validation.
=> validations: Enable reference validation of locals

go.mod
This reflects upstream changes as described in https://github.com/golang/go/issues/62278 and unblocks dependabot which currently cannot run.
An alternative fix would be to add `toolchain 1.21.0` but given that we don't need different version for compatibility and toolchain I think it's easier to just update the `go` directive for now.
See also https://github.com/dependabot/dependabot-core/issues/7895
=> go.mod: Fix go directive to include patch version

go.mod, go.sum, internal/indexer/document_change.go, internal/indexer/module_calls.go
Related: https://github.com/hashicorp/terraform-schema/pull/254
The PR is not strictly hard dependency for this one but it is helpful in testing, to verify that the race condition is no longer present.
--- 
Some time ago, we discovered a race condition, which may not have been as well understood at the time. We needed to make sure that go-to-definition and go-to-references works on first load for module inputs.
Module inputs are represented as reference origins and as with everything else, the attribute schema is what instructs the job collecting the reference origins how and whether to collect those origins. Obtaining the schema for _modules_ is basically the job of [`LoadModuleMetadata`](https://github.com/hashicorp/terraform-ls/blob/da68b876c05ac9b1e46697650d4785da8d498ed0/internal/terr …
=> indexer: Ensure declared module calls get decoded

internal/decoder/validations/unreferenced_origin.go
I was originally planning to raise issues to implement support for these origin types but after some research I realised implementing support wouldn't make much sense, so this PR just updates the relevant comments to reflect this.
=> decoder: Update comments about validation of other Origin types

.github/workflows/build-pr.yml, .github/workflows/test.yml
Since we started working with feature branches, such as `f-early-validation`, we lost our CI for branches that target that feature branch instead of `main`.
This PR enables the test workflow and build workflow for all PRs.
=> Run CI on PRs that don't target `main`

internal/terraform/ast/diagnostics.go
This PR updates the diagnostic source for all diagnostics we raise to `Terraform`. This makes the most sense from a user perspective, and we can extend this later by introducing codes for individual diagnostics.
=> Update diagnostic source to `Terraform`

internal/context/context.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/scheduler/scheduler_test.go, internal/state/jobs.go, internal/state/jobs_test.go, internal/state/module_changes_test.go, internal/walker/walker_test.go
This is to decouple a small part of https://github.com/hashicorp/terraform-ls/pull/1368 in order to help us make some more performance improvements unrelated to validation, specifically to avoid re-parsing _all_ files on `didOpen` and `didChange` and only parse the one which is being changed.
For end-users, this PR is expected to be no-op.
=> Introduce `RPCContext` to aid more fine-grained & efficient processing

go.mod, go.sum
This brings in https://github.com/hashicorp/hcl-lang/pull/318
The PR is expected to be no-op for users in the context of the `main` branch but I do expect us to need to make changes in https://github.com/hashicorp/terraform-ls/pull/1368 either in an isolated PR or as part of https://github.com/hashicorp/terraform-ls/pull/1413
The hope here is we can at least keep dependency changes in `main` and keep rebasing mostly free of conflicts.
=> deps: bump hcl-lang to `aa9b38d`

go.mod, go.sum, internal/decoder/decoder.go, internal/decoder/validators.go
This is another attempt to keep diffs small and resolve conflicts early.
We made some changes in https://github.com/hashicorp/hcl-lang/pull/318 and while cherry-picking the dependency bump to the feature branch, I'm also making updates to keep things working as before.
=> early validation - bump `hcl-lang` and reflect upstream changes

internal/context/context.go, internal/decoder/decoder_test.go, internal/terraform/ast/module.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/testdata/single-file-change-module/bar.tf, internal/terraform/module/testdata/single-file-change-module/example.tfvars, internal/terraform/module/testdata/single-file-change-module/foo.tf, internal/terraform/module/testdata/single-file-change-module/main.tf, internal/terraform/parser/module.go
This modifies ParseModuleConfiguration to only parse changed file if file already parsed and this is a didChange request.
Previously ParseModuleConfiguration would reparse not only the changed file but also the module containing the changed file.
Now ParseModuleConfiguration detects if the file has previously been parsed and the request is from a didChange event. If both are true, then it only parses the changed file and skips re-parsing the entire module. If this is false, it falls back to the previous behavior of re-parsing the entire module including the changed file.
=> Update ParseModuleConfiguration to only parse changed file

internal/decoder/decoder.go, internal/decoder/validators.go, internal/indexer/document_change.go, internal/indexer/document_open.go, internal/state/module.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go, internal/terraform/module/testdata/invalid-tfvars/foo.auto.tfvars, internal/terraform/module/testdata/invalid-tfvars/terraform.tfvars, internal/terraform/module/testdata/invalid-tfvars/variables.tf
Depends on:
- https://github.com/hashicorp/terraform-ls/pull/1412
- https://github.com/hashicorp/hcl-lang/pull/318
- https://github.com/hashicorp/terraform-ls/pull/1404 (strictly speaking it's "just" a performance improvement but it would likely make rebasing easier if it was merged first)
Closes https://github.com/hashicorp/terraform-ls/issues/1410
---
=> Introduce validation of `*.tfvars` files

internal/indexer/document_change.go
https://github.com/hashicorp/terraform-ls/pull/1395 added decoding of declared module calls with the intention that this happens before any other jobs run.
It turns out that depending on a job id will only waits for the completion of that job, but not for the jobs that are scheduled within the `Defer` function. Without waiting for the declared module calls or the origin collection, we publish diagnostics for stale origins (missing the last character).
By moving all subsequent jobs into the defer block, this PR pragmatically solves all problems.
* We now wait for the schema preloading before performing schema validation
* We now wait for the origin collection before running the reference validation
* We run all jobs in the correct order on change
=> Fix delayed diagnostics / job ordering

internal/context/context.go, internal/decoder/decoder.go, internal/decoder/validations/unreferenced_origin.go, internal/decoder/validations/unreferenced_origin_test.go, internal/decoder/validators.go, internal/indexer/document_change.go, internal/indexer/document_open.go, internal/langserver/diagnostics/diagnostics.go, internal/langserver/diagnostics/diagnostics_test.go, internal/langserver/handlers/command/validate.go, internal/langserver/handlers/hooks_module.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/settings/settings.go, internal/state/module.go, internal/state/module_changes.go, internal/state/module_test.go, internal/terraform/ast/diagnostics.go, internal/terraform/ast/module.go, internal/terraform/ast/variables.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go, internal/terraform/module/testdata/invalid-config/main.tf, internal/terraform/module/testdata/invalid-config/variables.tf, internal/terraform/module/testdata/invalid-tfvars/foo.auto.tfvars, internal/terraform/module/testdata/invalid-tfvars/terraform.tfvars, internal/terraform/module/testdata/invalid-tfvars/variables.tf
This PR merges the feature branch back into `main`
=> Early validation

internal/terraform/module/module_ops.go
This is to follow-up on one of the outcomes from our Deep Dive session yesterday.
=> Add comments explaining each job's purpose

go.mod, go.sum, internal/langserver/handlers/complete_test.go
This brings in the following changes related to the upcoming 1.6 release:
- https://github.com/hashicorp/terraform-schema/pull/257
- https://github.com/hashicorp/terraform-schema/pull/260
- https://github.com/hashicorp/terraform-schema/pull/261
- https://github.com/hashicorp/terraform-schema/pull/262
- https://github.com/hashicorp/terraform-schema/pull/263
- https://github.com/hashicorp/terraform-schema/pull/265
- https://github.com/hashicorp/terraform-schema/pull/266
- https://github.com/hashicorp/terraform-schema/pull/267
=> deps: Bump terraform-schema to `7b256e6c65f9`

internal/context/context.go, internal/decoder/decoder_test.go, internal/langserver/handlers/did_change.go, internal/langserver/handlers/did_open.go, internal/langserver/handlers/initialize.go, internal/langserver/handlers/service.go, internal/scheduler/scheduler_test.go, internal/state/jobs.go, internal/state/jobs_test.go, internal/state/module_changes_test.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/walker/walker_test.go
This ensures that we propagate the language ID between job scheduling and execution, which in turn enables https://github.com/hashicorp/terraform-ls/pull/1404 at runtime (and not just in unit tests).
While I am labelling this as a bug, it's a bug that was never surfaced to the user in a release, so it does not need to be mentioned in the Changelog AFAICT.
=> context: Replace `RPCContextData` with `DocumentContext`

go.mod, go.sum, internal/indexer/document_change.go, internal/indexer/document_open.go, internal/langserver/handlers/initialize.go, internal/settings/settings.go
This PR renames and enables the early validation setting by default. We use https://github.com/mcuadros/go-defaults to set a default value.
We could also rename the JSON `earlyValidation` key if we wanted, but in case that case we would need to update https://github.com/hashicorp/vscode-terraform/pull/1554 as well
=> Update early validation setting to `enabled` by default

internal/settings/settings.go
This is already (correctly) reflected in https://github.com/hashicorp/vscode-terraform/pull/1554 so no changes needed there.
This PR also should not need a Changelog entry since we never introduced the bug to a released version.
=> settings: Fix option name to `enableEarlyValidation`

internal/indexer/document_change.go
Prior to this patch we would skip running a number of jobs, including validation if loading metadata has failed.
Loading metadata can fail for example because `variable` block is incomplete. The `earlydecoder` should already provide partially decoded configuration anyway and hence enable the later validation, so we should not be blocking other jobs based on the failure here as we'd block useful diagnostics.
Similar to my other patch, this shouldn't need to be mentioned in the Changelog, since we have not yet exposed this bug to end users since we have not released validation yet.
=> fix: continue running jobs even if loading metadata fails

internal/settings/settings.go
This is slightly embarrassing in the context of https://github.com/hashicorp/terraform-ls/pull/1434 but it's _now_ correct, as confirmed via https://github.com/hashicorp/vscode-terraform/pull/1554
=> fix option name (early -> enhanced)

internal/terraform/ast/variables.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/testdata/single-file-change-module/example.tfvars, internal/terraform/module/testdata/single-file-change-module/nochange.tfvars, internal/terraform/parser/variables.go
Modifies ParsedVarsFiles to only re-parse the single tfvars file which is being changed, if the job was scheduled as part of `textDocument/didChange` request.
This is a follow up to https://github.com/hashicorp/terraform-ls/pull/1404 which updated the parsing job for terraform files.
=> Update ParseVariables for single files

go.mod, go.sum, internal/decoder/module_schema.go
This is to address:
- https://github.com/hashicorp/vscode-terraform/issues/1580
Depends on:
- https://github.com/hashicorp/terraform-schema/pull/275
--- 
This PR changes the meaning of the _version_ in the snippet of code being changed. Previously it referred to the discovered/installed Terraform version, whether or not we had the schema for it. With this patch, the meaning changes to "language/schema version".
In practice though it remains the same for the likely majority of cases (any stable version between `0.12` and `1.6`) but not for the other cases, where we fall back on either 0.12.0 or latest known version (currently 1.6.0).
Importantly, this does _not_ impact the discovered/installed version we persist and make available, e.g. here
Also, the new logic inside `ResolveVersion` …
=> Resolve version correctly for backend schema

go.mod, go.sum
This brings in
- https://github.com/hashicorp/hcl-lang/pull/333
=> deps: bump hcl-lang to 6ec57d47fbbb

go.mod, go.sum
This is to bring
- https://github.com/hashicorp/terraform-schema/pull/282
=> deps: bump terraform-schema to 3c628dc54764

internal/registry/module.go, internal/registry/module_test.go, internal/terraform/module/module_ops.go, internal/terraform/module/module_ops_mock_responses.go, internal/terraform/module/module_ops_test.go, internal/terraform/module/testdata/unreliable-inputs-module/main.tf
As discovered in https://github.com/hashicorp/vscode-terraform/issues/1582 it turns out that we assume inputs in some modules as required, when they are actually not.
- Why? - Because we use data from the Registry API, which (incorrectly) indicates some inputs as required.
- Which ones? - Modules which have "nullable" inputs (variables with `default = null`)
- Why? - Because the Registry API did not recognise "nullable" inputs at the time of ingesting the module.
- Can't the Registry fix this? - The Registry already recognises "nullable" inputs since 19th August 2022.
- Can't the Registry fix the data then? - This was considered but it involves potentially a _lot_ of modules and module versions, so this is a non-trivial task, esp. given that this would involve basically re-ingesting the …
=> fix: Work around 'unreliable' input data for Registry modules

internal/decoder/validations/unreferenced_origin.go
This is to provide further context/clarity inside of the codebase.
=> validations: Add link in comment to open issue

.github/ISSUE_TEMPLATE/performance.yml
This is mostly a copy-paste of the bug report issue template with a couple of questions removed that don't seem relevant.
=> Add new performance issue template

go.mod, go.sum
This PR brings in the latest updates from terraform-schema and hcl-lang.
terraform-schema:
* https://github.com/hashicorp/terraform-schema/pull/303
* https://github.com/hashicorp/terraform-schema/pull/302
* https://github.com/hashicorp/terraform-schema/pull/301
* https://github.com/hashicorp/terraform-schema/pull/295
* https://github.com/hashicorp/terraform-schema/pull/296
hcl-lang:
* https://github.com/hashicorp/hcl-lang/pull/326
* https://github.com/hashicorp/hcl-lang/pull/322
* https://github.com/hashicorp/hcl-lang/pull/344
=> Bump terraform-schema & hcl-lang

.github/CONTRIBUTING.md, .github/workflows/release.yml
Releasing currently requires a number of additional steps outside of GitHub. For a simple project with simple release pipeline such as this one, there is no strong benefit to do multi-staged releasing, as some other bigger projects do.
Simplify release process by moving promotion steps into a GHA workflow.
=> ci: Automate releasing via bob

internal/uri/uri.go, internal/uri/uri_test.go
This adds path detection for network WSL paths to warn the user to open the path in WSL instead.
A user can open a WSL path directly using the network mount path, which results in opening inside the host VS Code instance instead of inside the WSL instance. This is a problem for terraform-ls, which can't resolve the network paths correctly.
=> Alert on wsl.localhost Path

.github/workflows/benchmarks.yml, .github/workflows/build.yml
This reverts https://github.com/hashicorp/terraform-ls/pull/1571 as we seem to be affected by https://github.com/actions/download-artifact/issues/249 It is a correlation at this point but the number of upvotes and the timing makes it unlikely to be coincidence.
https://github.com/hashicorp/terraform-ls/actions/runs/7444848841/job/20252139726#step:4:16
I'm hoping to confirm the theory by downgrading back.
=> github: Revert upgrade of artifact actions

docs/syntax-highlighting.md, go.mod, go.sum, internal/lsp/completion.go, internal/lsp/symbols.go, internal/lsp/token_encoder.go
Depends on https://github.com/hashicorp/hcl-lang/pull/362
=> Rename `*Traversal*` to `*Reference*`

.github/workflows/build.yml
As discovered by @sarahethompson the new v4 version of the action we use now _requires_ this permission.
Not providing the permission leads to those artifacts to _not_ be deleted, which in turn trips up other workflows related to CRT which then attempt to upload these artifacts just because they are in the same path. CRT does not currently have path allowlist to ignore such artifacts but there is an internal feature request.
This is surfaced as the following error:
> `Error: -15T08:59:29.463Z [ERROR] bob: Failed to download workflow artifact: org=hashicorp repo=terraform-ls error="mkdir .bob/artifacts/registry.terraform.io/1password: permission denied"`
In retrospect it does make sense that in order to delete an artifact, one needs write permission of some kind. It is puzzling that this …
=> github: Grant `actions: write` permission

.github/workflows/build.yml
In spite of documentation saying the following
> ... requires a permissive [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), or a PAT with read and write access to actions.
which would imply that it just automatically reads that default `GITHUB_TOKEN`, we continue to see the following error:
> Error: Error: Parameter token or opts.auth is required
This is probably because [the action declares `token` as `required: true`](https://github.com/GeekyEggo/delete-artifact/blob/3f83cd6bfd1bb806746002ab8b59cc6f76f1740f/action.yml#L7) while also providing default. I don't understand how this is even valid combination on GitHub's side but we suspect this edge case is the root cause of the confusing behaviour.
=> github: Pass token explicitly to delete-artifact

go.mod, go.sum
This PR brings in the latest updates from terraform-schema and hcl-lang.
terraform-schema:
* https://github.com/hashicorp/terraform-schema/pull/315
* https://github.com/hashicorp/terraform-schema/pull/313
* https://github.com/hashicorp/terraform-schema/pull/314
hcl-lang: Nothing of note for the changelog.
=> Bump terraform-schema and hcl-lang

internal/uri/uri.go, internal/uri/uri_test.go
This reverts commit a5ff862d4afdad2415b346aba9c3e52f127b1ce1.
There have been several reports from users about problems with this change: https://github.com/hashicorp/terraform-ls/issues/1585, so we are rolling it back for now.
=> Revert "Alert on wsl.localhost Path (#1522)"

internal/langserver/handlers/symbols_test.go, internal/langserver/handlers/workspace_symbol_test.go, internal/lsp/symbols.go
This PR fixes two server panics related to symbols. The first one occurs when supported symbols are not part of the [TextDocumentClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentClientCapabilities) sent by the client. The second is when supported symbols are missing from the [workspace specific client capabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities).
In both cases, we now fall back to the list of symbols supported by the initial version of the protocol.
Closes https://github.com/hashicorp/terraform-ls/issues/1349
=> Fix LS panic on missing symbols in client capabilities 

README.md
I looked for this file in the root and in `docs/` initially but didn't think of the 
`.github` directory. I only learned this doc existed when Daniel happened to pull 
it up when doing the most recent patch release 😄
It is linked here due to being in that directory:
But that only is visible when creating a PR and it doesn't seem to be in this list in the sidebar:
=> docs: Link to .github/CONTRIBUTING.md in README

README.md
The comparison to terraform-lsp has been outdated for a long time
=> Remove outdated LSP comparison from README

internal/state/provider_schema.go
This PR removes the log line for accessing a provider schema in memory. We do this a lot and it causes a lot of noise in the log output.
It's also confusing because it might imply that there is an intensive operation involved, such as an HTTP request, which is not the case.
=> Remove getting provider schema log line

go.mod, go.sum
This brings in the latest changes to hcl-lang:
* https://github.com/hashicorp/hcl-lang/pull/375
=> Bump hcl-lang to `b482690`

internal/schemas/gen/gen.go
This is a temporary change to allow us to bundle provider schemas that include provider-defined functions.
It should be reverted after the Terraform 1.8 GA release.
=> Use Terraform 1.8-rc1 for bundling schemas

go.mod, go.sum, internal/decoder/functions.go
* Depends on https://github.com/hashicorp/terraform-schema/pull/336
* Closes https://github.com/hashicorp/terraform-ls/issues/1671
---
Prior to this PR, we would always merge any provider-defined functions included in a schema with the Terraform core functions. Even if the Terraform version doesn't support them yet.
=> Pass Terraform version to functions merger

go.mod, go.sum
This brings in the latest changes to
terraform-schema:
* https://github.com/hashicorp/terraform-schema/pull/337
* https://github.com/hashicorp/terraform-schema/pull/340
* https://github.com/hashicorp/terraform-schema/pull/338
* https://github.com/hashicorp/terraform-schema/pull/336
hcl-lang:
* none
=> Bump hcl-lang to `d90dc4d` & terraform-schema to `72025f5`

.github/workflows/build.yml
After the update to version 5.0.0, `token` is no longer required.
See:
* https://github.com/hashicorp/terraform-ls/actions/runs/8630067975/job/23655731728#step:2:1
* https://github.com/geekyeggo/delete-artifact/releases/tag/v5.0.0
=> Remove token from delete-artifact action

internal/terraform/exec/exec_test.go
Terraform 1.8.2 now includes a license file next to the binary. This isn't cleaned up by hc-install (yet), so we need to remove it for now.
This should resolve all recent test failures in PRs.
=> Remove non-empty directory during test cleanup

.github/workflows/issue-comment-created.yml
This PR replaces the unmaintained https://github.com/actions-ecosystem/action-remove-labels actions with a `gh` command.
This is part of the migration to Node 20 and should remove most of the warnings: https://github.com/hashicorp/terraform-ls/actions/runs/8958017076
=> Replace outdated remove-labels action with `gh`

.changes/unreleased/INTERNAL-20240614-105429.yaml, .github/CONTRIBUTING.md
I was looking for the command to generate them the other day and couldn't find it (it's in the Github workflows but I didn't look there 😅)
=> docs: document schema bundling in CONTRIBUTING.md

.changes/unreleased/INTERNAL-20240710-172718.yaml, .github/workflows/check-changelog.yml
This workflow checks for the adding or modification of files in the `.changie/unreleased` folder.
You can see it working for this PR
- The jobs fails for the first commit: https://github.com/hashicorp/terraform-ls/actions/runs/9876936239/job/27277296043?pr=1759
- After adding a changelog entry, it passes: https://github.com/hashicorp/terraform-ls/actions/runs/9877100325/job/27277866068?pr=1759
=> Introduce a workflow that checks for changelog entries

.changes/unreleased/ENHANCEMENTS-20240712-120348.yaml, go.mod, go.sum, internal/features/modules/decoder/decoder_test.go, internal/features/modules/decoder/path_reader.go, internal/features/modules/events.go, internal/features/modules/jobs/validation_test.go, internal/features/modules/state/module_store.go, internal/features/rootmodules/root_modules_feature.go, internal/features/rootmodules/state/installed_modules.go, internal/features/rootmodules/state/root_record.go, internal/features/rootmodules/state/root_store.go
* Requires https://github.com/hashicorp/terraform-schema/pull/366
* Closes https://github.com/hashicorp/vscode-terraform/issues/1440
* Closes https://github.com/hashicorp/vscode-terraform/issues/1280
* Closes https://github.com/hashicorp/terraform-ls/issues/1733
* Closes https://github.com/hashicorp/terraform-ls/issues/1604
---
This PR adds a missing piece from #1667: decoding declared module calls for locally installed modules (inside the `.terraform/` directory)
We do this by normalizing the value of the `source` attribute and matching it against entries in the module manifest. If we find a matching entry, we decode the contents of the folder. 
This not only re-enables it for registry modules, but also takes the approach a step further, allowing completion for (almost) any locally …
=> Decode declared modules for all kind of installed modules

go.mod, go.sum
This PR bumps terraform-schema to the latest commit on `main` after merging the pre-release branch. No new changes.
=> Bump terraform-schema to `d7b11d8`

.changes/unreleased/ENHANCEMENTS-20240716-094842.yaml, internal/features/stacks/ast/stacks.go, internal/features/stacks/events.go, internal/features/stacks/jobs/metadata.go, internal/features/stacks/state/stack_meta.go, internal/features/stacks/state/stack_record.go, internal/features/stacks/state/stack_store.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This commit adds a job to load the metadata for a stack. This metadata is used to decode the some of the configuration early before we have all the information we need to decode the full configuration. This is a first step towards decoding the full configuration of a stack.
=> (TF-18286) Add jobs to load Stack metadata

.changes/unreleased/INTERNAL-20240717-115636.yaml, go.mod, go.sum, internal/features/modules/jobs/schema.go, internal/features/stacks/events.go, internal/features/stacks/jobs/schema.go, internal/features/stacks/jobs/version_test.go, internal/features/stacks/stacks_feature.go, internal/features/stacks/state/schema.go, internal/features/stacks/state/stack_record.go, internal/features/stacks/state/stack_store.go, internal/state/provider_schema.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
Depends on https://github.com/hashicorp/terraform-schema/pull/375
---
This PR adds a job to load provider schemas that are embedded into the language server binary into state after the early decoder parsed which providers where used in a given stacks project. We will be going to use this information in the schema merger to e.g. enhance provider blocks with their respective attributes within the `config` block to support hover and completions.
=> feat: load embedded provider schemas for providers found in stacks files

.changes/unreleased/BUG FIXES-20240719-172514.yaml, internal/features/modules/jobs/schema.go, internal/features/modules/jobs/schema_mock_responses.go, internal/features/modules/jobs/schema_test.go, internal/features/modules/jobs/testdata/uninitialized-external-submodule/main.tf, internal/registry/module.go, internal/registry/module_test.go
Closes #1771 
Closes https://github.com/hashicorp/vscode-terraform/issues/1800
---
The registry client always used the Inputs and Outputs from the root module when fetching and storing a schema for a module with a registry address.
We now check if the source address contains a sub directory and use the Inputs and Outputs from the matching submodule.
=> Check for submodules when fetching schemas from the registry

.changes/unreleased/BUG FIXES-20240725-105238.yaml, internal/features/modules/events.go, internal/state/jobs.go
Moving the scheduling of both validation jobs into the Defer function ensures that they run after we loaded the schema, reference targets, and reference origins.
Before validation would run right after loading the metadata for a module without waiting on any of the work that we do in Defer.
Closes https://github.com/hashicorp/vscode-terraform/issues/1806
=> Schedule module validation jobs after within Defer

.changes/unreleased/ENHANCEMENTS-20240725-163756.yaml, go.mod, go.sum, internal/features/modules/modules_feature.go, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/events.go, internal/features/stacks/stacks_feature.go, internal/features/stacks/state/stack_store.go, internal/langserver/handlers/service.go, internal/langserver/handlers/session_mock_test.go
Merge all the schemas (for stacks stack files) 💯
This brings support for completions for `inputs` and `providers` in `component` blocks and for showing descriptions on hover among other schema related features. Note: this currently only supports local components with a source in a relative directory.
=> feat: use stacks schema merger

.changes/unreleased/ENHANCEMENTS-20240731-152949.yaml, go.mod, go.sum, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/state/stack_record.go
Uses the schema merger for stack deployment files to add completion and hover support for deployment blocks in deployment configuration.
=> deployments merge schemas

.changes/unreleased/ENHANCEMENTS-20240724-122601.yaml, internal/features/stacks/ast/stacks.go, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/decoder/validations/missing_required_attribute.go, internal/features/stacks/decoder/validations/valid_name.go, internal/features/stacks/decoder/validators.go, internal/features/stacks/events.go, internal/features/stacks/jobs/validation.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This change enables early validation for Terraform Stacks in tfstack. hcl and tfdeploy.hcl files.
Available validations:
- Missing required attributes
- Deprecated attributes
- Deprecated blocks
- Unexpected attributes
- Unexpected blocks
- Maximum number of blocks
- Minimum number of blocks
- Block labels length
This adds a new job to validate the schema of the these files. The job is enqueued when the `EnableEnhancedValidation` option is set to true.
=> (TF-18290) Early validation for Terraform Stack files

.changes/unreleased/ENHANCEMENTS-20240805-140526.yaml, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/events.go, internal/features/stacks/jobs/references.go, internal/features/stacks/state/stack_record.go, internal/features/stacks/state/stack_store.go
This commit adds two new jobs, DecodeReferenceOrigins and DecodeReferenceTargets, and their supporting plumbing to the stacks feature. These jobs are responsible for collecting reference origins and targets, respectively. Reference origins and targets are used to determine where a reference is defined and where it is used.
This information is useful for features like go-to-definition and go-to-references.
=> (TF-18664) Add DecodeReferenceOrigins and DecodeReferenceTargets jobs

.changes/unreleased/ENHANCEMENTS-20240816-154910.yaml, internal/features/stacks/decoder/deploy_functions.go, internal/features/stacks/decoder/path_reader.go
This adds support for a subset of the functions available in Terraform for deployment configuration.
For example, `sum` is not supported currently:
=> (TF-19244) feat: support a subset of functions in deployment configs

.changes/unreleased/ENHANCEMENTS-20240816-134804.yaml, go.mod, go.sum, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/state/stack_meta.go, internal/features/stacks/state/stack_store.go
Depends on https://github.com/hashicorp/terraform-schema/pull/390 to be merged and this PR to be updated with the squashed commit hash (_edit: done_)
=> feat: store early decoded deploy config and bump terraform-schema

.changes/unreleased/ENHANCEMENTS-20240815-135108.yaml, internal/features/stacks/decoder/validations/unreferenced_origins.go, internal/features/stacks/events.go, internal/features/stacks/jobs/validation.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
This commit adds a new validation to check for unreferenced origins in stack and deployment files. This validation is performed after the reference targets and origins are decoded.
The validation checks for references to variables and local values that do not have a corresponding target. The validation is performed for variables, local values, providers and identity_tokens only, as components can have unknown schema.
=> (TF-18673) Validate Stack and Deployment files for unreferenced origins

.changes/unreleased/BUG FIXES-20240823-102914.yaml, .changes/unreleased/ENHANCEMENTS-20240823-102940.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103027.yaml, .changes/unreleased/ENHANCEMENTS-20240823-103059.yaml, go.mod, go.sum
This PR updates `terraform-schema` to the latest main and ensures we have Changie entries for all PRs that landed in `terraform-schema` since the last release of Terraform LS.
=> Bump terraform-schema to `1800e4c`

.changes/unreleased/ENHANCEMENTS-20240822-123409.yaml, go.mod, go.sum, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/decoder/stack_functions.go
Depends on https://github.com/hashicorp/terraform-schema/pull/396
=> (TF-19616) feat: Support provider defined functions in stacks

.changes/unreleased/INTERNAL-20240913-111349.yaml, internal/features/stacks/stacks_feature.go, internal/langserver/handlers/hooks_module.go
A minimal addition to the existing telemetry data that lets us measure usage of the new stacks feature.
=> (TFECO-7524) chore: add Stacks Terraform version to telemetry

.changes/unreleased/BUG FIXES-20240924-105626.yaml, docs/USAGE.md
It looks like this was initially pointed out in the PR https://github.com/hashicorp/terraform-ls/pull/1802/files#r1726640328 but not addressed.
=> docs: Usage - Fix file extension

.changes/unreleased/INTERNAL-20241029-135512.yaml, docs/schema.md
This PR adds a document to explain how we handle provider schemas, so we can link to it.
=> Add a provider schema explainer doc

go.mod, go.sum, internal/features/stacks/decoder/path_reader.go, internal/features/stacks/events.go, internal/features/stacks/jobs/references.go, internal/features/stacks/jobs/validation.go, internal/features/stacks/stacks_feature.go, internal/langserver/handlers/service.go, internal/langserver/handlers/session_mock_test.go
This PR updates terraform-schema to `0438899ff948` which requires a new `InstalledModulePath` method. To comply with the updated interface, we need to pass the root feature to the stacks feature.
This should unblock 
* https://github.com/hashicorp/terraform-ls/pull/1850
* https://github.com/hashicorp/terraform-ls/pull/1854
So both can be reviewed and merged independently of https://github.com/hashicorp/terraform-ls/pull/1836.
To avoid this in the future, we should refrain from merging terraform-schema PRs that contain interface or struct changes until their terraform-ls counterpart has been reviewed & approved
=> Minimal API changes to unblock PRs

.changes/unreleased/ENHANCEMENTS-20241107-164703.yaml, go.mod, go.sum, internal/features/stacks/jobs/metadata.go, internal/langserver/handlers/initialize_test.go
This change updates the stack metadata loading to merge the new diagnostics with the existing ones. This is necessary to ensure that we don't lose any diagnostics that were previously reported.
Needs https://github.com/hashicorp/terraform-schema/pull/412
=> (TFECO-7637) Raise HCL diagnostics

.changes/unreleased/INTERNAL-20241120-134148.yaml, META.d/_summary.yml, META.d/data.yml
This change adds the metadata for the internal Heimdall service to the repository.
=> (TFECO-8260) Add Heimdall metadata

.changes/unreleased/INTERNAL-20241128-173155.yaml, internal/langserver/handlers/workspace_symbol_test.go
In the `workspace/symbol` tests, we'll send multiple `didOpen` requests for files in the same directory. The first request will trigger parsing of the whole directory (which is empty on disk) and set the module state to "loaded". The second `didOpen` will then do nothing, as it will respect the state already marked as loaded.
Depending on the order of execution, sometimes both files are opened before the first parsing job runs, sometimes the job runs between the two calls, causing the test to fail.
By writing the files to disk first, we ensure that both are parsed by the first `didOpen` call.
=> Fix flaky `workspace/symbol` tests

.changes/unreleased/INTERNAL-20241202-134258.yaml, internal/features/modules/modules_feature.go, internal/features/rootmodules/root_modules_feature.go, internal/langserver/handlers/initialize_test.go
This is PR `#2` of the "reducing CI flakiness" project.
We now wait for all directories found to be persisted in state during the workspace walk. This ensures that later operations will have access to the complete state.
---
Related
* https://github.com/hashicorp/terraform-ls/pull/1880
=> Fix flaky initialize handler tests

.changes/unreleased/BUG FIXES-20241203-144106.yaml, go.mod, go.sum
This PR brings in the following changes from hcl-lang:
* https://github.com/hashicorp/hcl-lang/pull/432
The local `a` is a tuple with specific element types. The for-expression has an empty tuple as a constraint, which doesn't match the specific element types. We now short-circuit the convertible check and always mark empty tuples as matching.
Fixes https://github.com/hashicorp/vscode-terraform/issues/1708
=> Fix incorrect validation for heterogeneous list

.changes/unreleased/BUG FIXES-20241209-151045.yaml, go.mod, go.sum
This brings in the changes from hcl-lang:
* https://github.com/hashicorp/hcl-lang/pull/434
While this doesn't improve completion due to the missing nested targets, it does improve the UX on hover, go-to-*, and validation.
Closes #1867
=> Fix incorrect validation for for-expressions

.changes/unreleased/BUG FIXES-20241219-152506.yaml, internal/features/rootmodules/state/root_store.go
#1836 added support for parsing `terraform-sources.json` files present in stacks projects. As the `modules.json` and the `terraform-sources.json` files are mutually exclusive and thus not expected to be present at the same time, that PR re-used the existing `InstalledModules` for simplicity. However, it thereby accidentally introduced a race between the two jobs looking for and parsing these files. In the case of https://github.com/hashicorp/vscode-terraform/issues/1915, the job parsing `terraform-sources.json` terminated second and overwrote `InstalledModules` with `nil` as no manifest file was found.
This PR adds a simple fix to only overwrite `InstalledModules` if it is not `nil` – this is just a short-term bandaid however, given it might lead to stale data. For a long-term fix, we …
=> fix modules.json and terraform-sources.json overriding each other

.changes/unreleased/ENHANCEMENTS-20250117-164515.yaml, go.mod, go.sum, internal/features/modules/events.go, internal/features/modules/jobs/write_only_attributes.go, internal/features/modules/modules_feature.go, internal/features/modules/state/module_record.go, internal/features/modules/state/module_store.go, internal/features/modules/state/write_only_attributes.go, internal/terraform/module/operation/op_type_string.go, internal/terraform/module/operation/operation.go
* https://github.com/hashicorp/hcl-lang/pull/442
* https://github.com/hashicorp/terraform-schema/pull/443
---
This PR adds a job that counts usages of write-only attributes. Currently the editor supports these but does not offer special handling in the case of ephemeral values (e.g. ephemeral values can be passed to write-only attributes but not to "normal" ones). By reporting telemetry of these we can learn about their usage in the wild and properly prioritize related features improving their usage.
=> feat: Report usage of write-only attributes for public providers

.changes/unreleased/ENHANCEMENTS-20250918-122900.yaml, go.mod, go.sum
Supports static schemas for terraform action. Bumped terraform-schema version
- https://github.com/hashicorp/terraform-schema/pull/477
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> Support for Terraform Action Static Schema

.changes/v0.38.0.md, CHANGELOG.md
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.
=> docs: update changelog entry for v0.38.0
