hashicorp/terraform-ls

docs/USAGE.md

It's not ideal UX, but I thought it's still better to provide suboptimal answer than no answer. 🤷‍♂️

docs: Add usage instructions for IntelliJ

---

commands/completion_command.go
internal/terraform/discovery/discovery.go
internal/terraform/discovery/discovery_mock.go
langserver/handlers/service.go
langserver/handlers/service_mock.go

terraform/discovery: Mock LookPath calls

---

internal/terraform/discovery/discovery.go
internal/terraform/discovery/discovery_unix.go
internal/terraform/discovery/discovery_windows.go

terraform/discovery: Find exe on Windows explicitly

---

.github/workflows/main.yml
.goreleaser.yml

build: Publish artifacts to releases.hashicorp.com

---

.hashibot.hcl

Add Hashibot configuration

---

.github/workflows/release.yml
.goreleaser.yml

goreleaser: publish Homebrew formula

---

internal/terraform/exec/exec.go
internal/terraform/exec/exec_test.go
internal/terraform/rootmodule/root_module_manager_mock_test.go
internal/terraform/rootmodule/root_module_manager_test.go
langserver/handlers/complete_test.go
langserver/handlers/formatting_test.go
langserver/handlers/handlers_test.go
langserver/handlers/initialize_test.go

This fixes #145 .
I tested in my local environment (macOS) with VSCode and it worked as expected.

Pass -no-color to terraform

---

.goreleaser.yml

As per https://goreleaser.com/customization/build/#reproducible-builds

goreleaser: Reproducible builds

---

commands/serve_command.go
internal/context/context.go
langserver/handlers/service.go

Paying back some tech debt as discussed in https://github.com/hashicorp/terraform-ls/pull/198#discussion_r452973029

internal/context: make context first argument

---

.github/workflows/ci.yml

https://github.com/codecov/codecov-action/issues/100 was resolved.

build: Pin codecov Action to v1

---

docs/SETTINGS.md
go.mod
go.sum
langserver/handlers/initialize.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/go.mod
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/modules.txt

Support 'homedir' ~ in root module paths

---

go.mod
go.sum
langserver/handlers/did_open.go
langserver/handlers/initialize.go
vendor/github.com/creachadair/jrpc2/base.go
vendor/github.com/creachadair/jrpc2/client.go
vendor/github.com/creachadair/jrpc2/ctx.go
vendor/github.com/creachadair/jrpc2/doc.go
vendor/github.com/creachadair/jrpc2/go.mod
vendor/github.com/creachadair/jrpc2/go.sum
vendor/github.com/creachadair/jrpc2/opts.go
vendor/github.com/creachadair/jrpc2/server.go
vendor/github.com/google/go-cmp/cmp/compare.go
vendor/github.com/google/go-cmp/cmp/report_compare.go
vendor/github.com/google/go-cmp/cmp/report_reflect.go
vendor/github.com/google/go-cmp/cmp/report_slices.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/modules.txt

This brings in some useful improvements, such as support for [server-side callbacks](https://github.com/creachadair/jrpc2/pull/25) which we might need e.g. for https://github.com/hashicorp/terraform-ls/issues/106
It also contains https://github.com/creachadair/jrpc2/pull/24 which fixes #161

deps: Bump creachadair/jrpc2 to latest (0.10.0)

---

langserver/handlers/symbols.go

Rename file to plural, matching test file

Switch symbol kind to SKClass as discussed

---

internal/lsp/completion.go

--- 
It is worth noting that this flag may not be available for all providers, because it was introduced in plugin protocol 5.2 (SDK v2 AFAIK) which not all providers have migrated to yet.

Report deprecated completion items as such

---

internal/schemas/gen/gen.go

The verified partner providers was getting close to the max page size (100)

Paginate registry results

---

.github/workflows/release.yml
.goreleaser.yml

**This PR should not be merged until we are ready to switch the bucket over.**
New env vars have been added. 
Existing env vars can be removed once this PR is merged.

DO NOT MERGE - [RE-206] - moving hc-releases s3 bucket to a new AWS account

---

.goreleaser.yml

Follow-up on #412 and #413 
Third time is the charm, or at least I hope. 😄  🤞🏻

goreleaser: Fix release job by passing the right ENV vars

---

go.mod
go.sum

deps: Reflect 0.15 schema changes

---

go.mod
go.sum

Closes #425 
Closes #447 
--- 
Includes:
- https://github.com/hashicorp/terraform-schema/pull/31
- https://github.com/hashicorp/hcl-lang/pull/29
- https://github.com/hashicorp/hcl-lang/pull/28

Bump hashicorp/terraform-schema to 18d878a488bf

---

go.mod
go.sum
internal/langserver/handlers/complete_test.go
internal/langserver/handlers/document_link_test.go
internal/state/module.go
internal/state/module_test.go
internal/state/provider_schema.go
internal/state/provider_schema_test.go

Depends on https://github.com/hashicorp/terraform-schema/pull/39
Closes #471
--- 
```
go test -run=XXX -bench=. ./internal/state
```
```
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/terraform-ls/internal/state
cpu: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
BenchmarkModuleByPath-4     	    3937	    268528 ns/op
BenchmarkProviderSchema-4   	   58588	     20559 ns/op
PASS
ok  	github.com/hashicorp/terraform-ls/internal/state	3.495s
```
```
go test -run=XXX -bench=. ./internal/state
```
```
goos: darwin
goarch: amd64
pkg: github.com/hashicorp/terraform-ls/internal/state
cpu: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
BenchmarkModuleByPath-4     	    9272	    116078 ns/op
BenchmarkProviderSchema-4   	  104325	     11234 ns/op
PASS
ok  	github.com/hashicorp/terraform-ls/internal/state …
```

state: Copy data on write - not on read

---

docs/TROUBLESHOOTING.md
internal/cmd/serve_command.go
internal/logging/logging.go
internal/pathtpl/pathtpl.go

support templated paths for cpuprofile & memprofile

---

go.mod
go.sum
internal/langserver/handlers/complete_test.go
internal/state/provider_schema_test.go

This brings in the following:
- https://github.com/hashicorp/terraform-schema/pull/53
- https://github.com/hashicorp/terraform-schema/pull/54
- https://github.com/hashicorp/hcl-lang/pull/42
- https://github.com/hashicorp/hcl-lang/pull/43
- https://github.com/hashicorp/hcl-lang/pull/47
- https://github.com/hashicorp/hcl-lang/pull/48
- https://github.com/hashicorp/hcl-lang/pull/49
which in turn
Closes #490

Bump hashicorp/terraform-schema to 8f289892

---

go.mod
go.sum
internal/terraform/module/module_manager.go

Fixes #285 
Depends on hashicorp/terraform-schema#52

Add support for state backends

---

docs/language-clients.md

cc @beandrad @Nepomuceno FYI for the future PR related to tfvars support in the VS Code extension.

docs: Add notes for language clients

---

go.mod
go.sum

Closes https://github.com/hashicorp/terraform-ls/issues/491

Support for references to vars and locals

---

go.mod
go.sum

Fixes #552
Depends on https://github.com/hashicorp/hcl-lang/pull/54
Depends on https://github.com/hashicorp/terraform-schema/pull/60

Prevent var names from being completed in label

---

go.mod
go.sum

This brings in https://github.com/hashicorp/hcl-lang/pull/64
Fixes https://github.com/hashicorp/terraform-ls/issues/573

fix: avoid circular references to list/map/object attributes

---

internal/hcl/diff.go
internal/hcl/diff_test.go

fix: avoid crash on empty file formatting

---

go.mod
go.sum
internal/decoder/decoder.go
internal/langserver/handlers/did_change.go
internal/langserver/handlers/did_open.go
internal/langserver/handlers/handlers_test.go
internal/langserver/handlers/initialize.go
internal/langserver/handlers/references.go
internal/langserver/handlers/references_test.go
internal/langserver/handlers/service.go
internal/lsp/locations.go
internal/state/module.go
internal/terraform/module/module_loader.go
internal/terraform/module/module_ops.go
internal/terraform/module/operation/op_type_string.go
internal/terraform/module/operation/operation.go

Depends on https://github.com/hashicorp/hcl-lang/pull/63
--- 
--- 
Just for posterity - a code lens showing number of references above each block will be part of a separate future PR.

Go to references (addresses)

---

docs/language-clients.md
go.mod
go.sum
internal/langserver/handlers/code_lens.go
internal/langserver/handlers/code_lens_test.go
internal/langserver/handlers/command/init.go
internal/langserver/handlers/command/module_callers.go
internal/langserver/handlers/command/modules.go
internal/langserver/handlers/command/validate.go
internal/langserver/handlers/initialize.go
internal/langserver/handlers/service.go
internal/lsp/range.go
internal/protocol/experimental.go

Closes #254 
Depends on https://github.com/hashicorp/hcl-lang/pull/69

Implement reference count code lens

---

go.mod
go.sum

Fixes https://github.com/hashicorp/terraform-ls/issues/600

fix: recognize list(object) and set(object) attributes as blocks

---

go.mod
go.sum

Fixes https://github.com/hashicorp/terraform-ls/issues/611

fix: avoid crash on missing block label

---

docs/language-clients.md

This is documentation for language clients to complement a recently merged PR: https://github.com/hashicorp/terraform-ls/pull/790
Here is a draft PR of what an implementation based on these docs may look like:
https://github.com/hashicorp/vscode-terraform/pull/1095

docs: Document watched files

---

internal/schemas/gen/gen.go

- See https://github.com/lightstep/terraform-provider-lightstep/issues/89
- https://registry.terraform.io/providers/thousandeyes/thousandeyes/latest does not have any stable release yet

schemas: Exclude lightstep/lightstep

---

internal/terraform/module/types.go
internal/terraform/module/walker.go

This is some dead code which I just forgot to remove as part of https://github.com/hashicorp/terraform-ls/pull/953

walker: remove last occurence of old watcher

---

.github/gobenchdata-checks.yml

See https://github.com/hashicorp/terraform-ls/runs/7085408391?check_suite_focus=true

ci: lower benchmark threshold for k8s-dashboard

---

go.mod
go.sum

Changelog:
- https://github.com/hashicorp/terraform-schema/pull/115
- https://github.com/hashicorp/terraform-schema/pull/117

deps: bump terraform-schema to e05b3dd5db1d

---

docs/USAGE.md

Tracking of paths outside the workspace can be re-evaluated as part of https://github.com/hashicorp/terraform-ls/issues/996

docs: Clarify usage of workspaces

---

docs/benchmarks.md

Not something I'm particularly happy about seeing, but at least it reflects the current state and makes it more obvious that we'll need to work on reducing the memory usage.

docs: Update benchmarks

---

.goreleaser.yml
internal/schemas/gen/gen.go

See https://github.com/oracle/terraform-provider-oci/issues/1650

schemas: exclude oci from schema generation

---

CHANGELOG.md
go.mod
go.sum

For completion, hover documentation and semantic tokens highlighting

Support `each.*` references in blocks with `for_each`

---

docs/USAGE.md

Closes https://github.com/hashicorp/terraform-ls/issues/1068

docs: Update VS Code usage instructions

---

CHANGELOG.md

This PR updates the changelog with an extra note about the location of the release assets.

Update changelog / docs about release assets

---

docs/USAGE.md

Add instructions for KDE Kate code editor

Add instructions for Kate editor

---

go.mod
go.sum

This is to bring in support for nested expressions and functions.

deps: Bump hcl-lang & terraform-schema to latest revs

---

docs/syntax-highlighting.md
internal/langserver/handlers/semantic_tokens_test.go
internal/lsp/token_encoder.go

Depends on https://github.com/hashicorp/hcl-lang/pull/232

lsp: Recognise new token type for function name

---

go.mod
go.sum

Pulls in https://github.com/hashicorp/hcl-lang/pull/275

Bump hcl-lang to `6430b4`

---

go.mod
go.sum

Depends on:
- https://github.com/hashicorp/terraform-schema/pull/235
- https://github.com/hashicorp/terraform-schema/pull/236

deps: bump terraform-schema to latest rev

---

CHANGELOG.md

This assumes merge of https://github.com/hashicorp/terraform-ls/pull/1422

Update Changelog for 0.32.0

---

go.mod
go.sum

This brings in the following changes:
- https://github.com/hashicorp/terraform-schema/pull/272
- https://github.com/hashicorp/terraform-schema/pull/271
- https://github.com/hashicorp/hcl-lang/pull/330

deps: bump hcl-lang & terraform-schema to apply bug fixes

---

go.mod
go.sum

This brings in
- https://github.com/hashicorp/terraform-schema/pull/279

deps: Bump terraform-schema to 2e7ddf929411

---

docs/syntax-highlighting.md

docs: update syntax-highlighting.md

---

go.mod
go.sum
internal/langserver/handlers/complete.go
internal/langserver/handlers/complete_test.go

* Depends on https://github.com/hashicorp/hcl-lang/pull/356
* Depends on https://github.com/hashicorp/terraform-schema/pull/311

Rename `CandidatesAtPos` to `CompletionAtPos`

---

docs/USAGE.md

I use the `YouCompleteMe` code completer for vim alongside `terraform-ls`. I noticed that there wasn't any documentation for it, so I figured it should be included.

Add documentation for YouCompleteMe

---

.changes/unreleased/ENHANCEMENTS-20240625-145639.yaml
.changes/unreleased/ENHANCEMENTS-20240625-145657.yaml
go.mod
go.sum

This pulls in the latest changes from terraform-schema:
* https://github.com/hashicorp/terraform-schema/pull/358
* https://github.com/hashicorp/terraform-schema/pull/357

Bump terraform-schema to `d94934b`

---

internal/features/stacks/decoder/path_reader.go

Each context needs its own set of references and files.

Create separate path contexts for Stack and Deploy

---

go.mod
go.sum
internal/features/modules/ast/module.go
internal/features/stacks/ast/stacks.go
internal/features/stacks/decoder/path_reader.go
internal/features/stacks/events.go
internal/features/stacks/jobs/parse_stack.go
internal/features/stacks/jobs/types.go
internal/features/stacks/parser/stacks.go
internal/features/stacks/stacks_feature.go
internal/features/stacks/state/schema.go
internal/features/stacks/state/stack_meta.go
internal/features/stacks/state/stack_record.go
internal/features/stacks/state/stack_store.go
internal/langserver/handlers/did_change_watched_files_test.go
internal/langserver/handlers/hooks_module.go
internal/langserver/handlers/initialize_test.go
internal/langserver/handlers/service.go
internal/langserver/handlers/session_mock_test.go
internal/lsp/language_id.go
internal/terraform/module/operation/op_type_string.go
internal/terraform/module/operation/operation.go

This commit adds initial support for Terraform Stacks files and Deployment files. This provides completion, hover, and diagnostics for Terraform Stacks and Deployment files.
Needs https://github.com/hashicorp/terraform-schema/pull/346

Implement support for Terraform Stacks

---

.changes/unreleased/ENHANCEMENTS-20240829-140210.yaml
go.mod
go.sum
internal/features/stacks/decoder/path_reader.go
internal/features/stacks/jobs/builtin_references.go
internal/features/stacks/jobs/references.go
internal/features/stacks/state/stack_meta.go
internal/features/stacks/state/stack_store.go

depends on https://github.com/hashicorp/terraform-schema/pull/398

(TFECO-7339) feat: Support context references within orchestrate blocks in deployment configuration

---

.changes/unreleased/INTERNAL-20241128-145742.yaml
internal/features/stacks/jobs/parse_test.go
internal/features/stacks/jobs/schema_test.go
internal/features/stacks/jobs/testdata/invalid-stack/deployments.tfdeploy.hcl
internal/features/stacks/jobs/testdata/invalid-stack/variables.tfstack.hcl
internal/features/stacks/jobs/testdata/simple-stack/components.tfstack.hcl
internal/features/stacks/jobs/testdata/simple-stack/deployments.tfdeploy.hcl
internal/features/stacks/jobs/testdata/simple-stack/variables.tfstack.hcl
internal/features/stacks/jobs/validation_test.go
internal/features/stacks/state/stack_store_test.go

This PR adds a couple of tests for Stacks related jobs and the Stacks state store.

Add tests for Stacks feature

---

internal/langserver/handlers/initialize_test.go

This should help debugging the flaky handler tests

Fix test output and add log statements

---

.changes/unreleased/INTERNAL-20241219-112751.yaml
go.mod
go.sum

- **Bump golang.org/x/net from 0.32.2 to 0.33.0**
- **changelog**

Bump golang.org/x/net from 0.32.2 to 0.33.0

---

.changes/unreleased/ENHANCEMENTS-20250929-140122.yaml
go.mod
go.sum

Supports dynamic schemas for terraform action. Bumped terraform-schema version
- https://github.com/hashicorp/terraform-schema/pull/482
https://github.com/user-attachments/assets/8ad11866-b48a-4801-bd6b-c41fd50aa931
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, etc.

Supports dynamic schemas for terraform action
